apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeployment
metadata:
  name: osh-dev
  namespace: openstack
  labels: {}
  annotations: {}
spec:
  openstack_version: stein
  profile: base
  domain_name: kaas-kubernetes-3af5ae538cf411e9a6c7fa163e5a4837
  # features that would enable coordinated changes to values of several charts
  features:
    services:
     - block-storage
     - compute
     - identity
     - dashboard
     - image
     - ingress
     - database
     - memcached
     - networking
     - orchestration
     - messaging
     - load-balancer
     - dns
     - key-manager
    ssl:
      public_endpoints:
        enabled: True
    barbican:
      backend:
        simple_crypto:
          enabled: True
          kek: 'YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY='
    keystone:
      keycloak:
        oidc:
          # SSL validation have to be disabled until upstream bug
          # https://github.com/zmartzone/mod_auth_openidc/issues/329 is not
          # fixed and CA is custom.
          OIDCSSLValidateServer: false
    glance:
      backend: ceph
    cinder:
      volume:
        backend: ceph
      backup:
        backend: ceph
    neutron:
      backend: ovs
      external_networks:
        - physnet: external
          interface: veth-phy
          bridge: br-ex
          network_types:
           - flat
          vlan_ranges: null
          mtu: null

    nova:
      images:
        backend: local
    stacklight:
      enabled: true
  # enabled services and their specific configuration
  services:
    identity:
      keystone:
        values:
          conf:
            keystone:
              DEFAULT:
               mykey: myvalue
    image:
      glance:
        values:
          bootstrap:
            enabled: true
            ks_user: admin
            structured:
              images:
                cirros:
                  container_format: bare
                  image_file: cirros-0.4.0-x86_64-disk.img
                  image_type: qcow2
                  min_disk: 1
                  name: Cirros-4.0
                  private: false
                  properties:
                    os_distro: cirros
                  source_url: https://artifactory.mcp.mirantis.net/artifactory/test-images/
                fedora:
                  container_format: bare
                  image_file: Fedora-Cloud-Base-27-1.6.x86_64.qcow2
                  image_type: qcow2
                  min_disk: 1
                  name: Fedora-27-1.6
                  private: false
                  properties:
                    os_distro: fedora
                  source_url: https://artifactory.mcp.mirantis.net/artifactory/test-images/
    compute:
      nova:
        values:
          bootstrap:
            structured:
              flavors:
                options:
                  m1.extra_tiny_test:
                    disk: 5
                    name: m1.extra_tiny_test
                    ram: 256
                    vcpus: 1
                  m1.tiny_test:
                    disk: 5
                    name: m1.tiny_test
                    ram: 512
                    vcpus: 1
    networking:
      neutron:
        values:
          bootstrap:
            enabled: true
            script: |
              openstack network create \
                --provider-network-type flat \
                --provider-physical-network external \
                --external \
                public
              openstack subnet create public-subnet \
                --no-dhcp --subnet-range 10.11.12.0/24 \
                --allocation-pool start=10.11.12.100,end=10.11.12.200 \
                --gateway 10.11.12.10 \
                --network public
              openstack router create r1
              openstack router set --external-gateway public r1
    tempest:
      tempest:
        values:
          conf:
            convert_to_uuid:
              network:
                public_network_id: public
              compute:
                image_ref: Cirros-4.0
                image_ref_alt: Cirros-4.0
                flavor_ref:  m1.extra_tiny_test
                flavor_ref_alt: m1.tiny_test
            blacklist:
              - (?:tempest\.fake\.test)
              - (?:heat_tempest_plugin\.)
              - (?:designate_tempest_plugin\.)
            script: |
              tempest run --config-file /etc/tempest/tempest.conf -w 4 --smoke --blacklist-file  /etc/tempest/test-blacklist
            tempest:
              dashboard:
                disable_ssl_certificate_validation: true
              validation:
                image_ssh_password: gocubsgo
                image_ssh_user: cirros
              network:
                shared_physical_network: false
                floating_network_name: public
    load-balancer:
      octavia:
        values:
          octavia:
            settings:
              amphora_image_url: "http://images.mcp.mirantis.net/octavia/amphora-x64-haproxy-stein-testing.qcow2"
