apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeployment
metadata:
  name: osh-dev
  namespace: openstack
  labels: {}
  annotations: {}
spec:
  # base set of values to base on
  base: null
  # common values to pass into all charts and services
  common:
    images:
      repo:
    # Common data among all charts
    charts:
      releases:
        version: 0.1.0
        namespace: openstack
        values:
          endpoints:
            cluster_domain_suffix: kaas-kubernetes-3af5ae538cf411e9a6c7fa163e5a4837
      repositories:
      - name: osh
        url: "https://harbor.mcp.mirantis.net/chartrepo/mcp-openstack-helm-20190611103255"
      - name: osh-infra
        url: "https://harbor.mcp.mirantis.net/chartrepo/mcp-openstack-helm-infra-20190611103603"
    # Common data among all chart groups
    openstack:
      repo: osh
      version: stein
    infra:
      repo: osh-infra
  # features that would enable coordinated changes to values of several charts
  features:
    messaging:
      dedicated_rabbitmq:
        enabled: True
    keystone:
      iam:
        enabled: True
    glance:
      direct_upload: False
      backend: ceph
    cinder:
      volume:
        backend: ceph
      backup:
        backend: radosgw
    neutron:
      backend: ovs
    nova:
      image_backend: ceph
  # enabled services and their specific configuration
  services:
    ingress:
      values: {}
    memcached:
      values: {}
    mariadb:
      values: {}
    rabbitmq:
      values: {}
    keystone:
      values: {}
    glance:
      values: {}
    cinder:
      values: {}
    neutron:
      values: {}
    nova:
      values: {}
    heat:
      values: {}
    horizon:
      values: {}
