apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeployment
metadata:
  name: osh-dev
  namespace: openstack
  labels: {}
  annotations: {}
spec:
  openstack_version: stein
  profile: base
  domain_name: kaas-kubernetes-3af5ae538cf411e9a6c7fa163e5a4837
  # features that would enable coordinated changes to values of several charts
  features:
    services:
     - block-storage
     - compute
     - identity
     - dashboard
     - image
     - ingress
     - mariadb
     - memcached
     - networking
     - orchestration
     - rabbitmq
    ssl:
      public_endpoints:
        enabled: True
    keystone:
      users:
        admin:
          username: admin
          password: workshop
    glance:
      backend: ceph
    cinder:
      volume:
        backend: ceph
      backup:
        backend: ceph
    neutron:
      backend: ovs
    nova:
      images:
        backend: local
  # enabled services and their specific configuration
  services:
    identity:
      keystone:
        values:
          conf:
            keystone:
              DEFAULT:
               mykey: myvalue
    image:
      glance:
        values:
          bootstrap:
            enabled: true
            ks_user: admin
            structured:
              images:
                cirros:
                  container_format: bare
                  id: 00000000-0000-0000-0000-000000000000
                  image_file: cirros-0.4.0-x86_64-disk.img
                  image_type: qcow2
                  min_disk: 1
                  name: Cirros-4.0
                  private: false
                  properties:
                    os_distro: cirros
                  source_url: https://artifactory.mcp.mirantis.net/artifactory/test-images/
                fedora:
                  container_format: bare
                  id: 00000000-0000-0000-0000-000000000001
                  image_file: Fedora-Cloud-Base-27-1.6.x86_64.qcow2
                  image_type: qcow2
                  min_disk: 1
                  name: Fedora-27-1.6
                  private: false
                  properties:
                    os_distro: fedora
                  source_url: https://artifactory.mcp.mirantis.net/artifactory/test-images/
    compute:
      nova:
        values:
          bootstrap:
            structured:
              flavors:
                options:
                  m1.extra_tiny_test:
                    disk: 1
                    id: 00000000-0000-0000-0000-000000000000
                    name: m1.extra_tiny_test
                    ram: 256
                    vcpus: 1
                  m1_tiny_test:
                    disk: 1
                    id: 00000000-0000-0000-0000-000000000001
                    name: m1.tiny_test
                    ram: 512
                    vcpus: 1
    tempest:
      tempest:
        values:
          conf:
            blacklist:
            # TODO(sandrichenko) create a bugs for each of failures/group of failures and assign to appropriate team.
            - (?:tempest\.scenario\.test_server_basic_ops\.TestServerBasicOps\.test_server_basic_ops)
            - (?:tempest\.api\.volume\.test_volumes_actions\.VolumesActionsTest)
            - (?:tempest\.api\.volume\.test_volumes_get\.VolumesGetTest\.test_volume_create_get_update_delete_from_image)
            - (?:tempest\.api\.volume\.test_volumes_get\.VolumesGetTest\.test_volume_create_get_update_delete)
            - (?:tempest\.api\.volume\.test_volumes_list\.VolumesListTestJSON)
            - (?:tempest\.api\.compute\.servers\.test_server_actions\.ServerActionsTestJSON)
            - (?:tempest\.api\.compute\.servers\.test_create_server\.ServersTestManualDisk)
            - (?:tempest\.api\.compute\.servers\.test_attach_interfaces\.AttachInterfacesUnderV243Test\.test_add_remove_fixed_ip)
            - (?:tempest\.api\.compute\.servers\.test_server_addresses\.ServerAddressesTestJSON)
            - (?:tempest\.api\.compute\.servers\.test_create_server\.ServersTestBootFromVolume)
            - (?:tempest_horizon\.tests.scenario\.test_dashboard_basic_ops\.TestDashboardBasicOps\.test_basic_scenario)
            - (?:tempest\.api\.compute\.servers\.test_create_server\.ServersTestJSON)
            script: |
              tempest run --config-file /etc/tempest/tempest.conf -w 4 --smoke --blacklist-file  /etc/tempest/test-blacklist
            tempest:
              compute:
                image_ref: 00000000-0000-0000-0000-000000000000
                image_ref_alt: 00000000-0000-0000-0000-000000000001
                flavor_ref: 00000000-0000-0000-0000-000000000000
                flavor_ref_alt: 00000000-0000-0000-0000-000000000001