apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeployment
metadata:
  name: osh-dev
  namespace: openstack
  labels: {}
  annotations: {}
spec:
  # common values to pass into all charts and services
  common:
    images:
      repo:
    # Common data among all charts
    charts:
      releases:
        values:
          endpoints:
            cluster_domain_suffix: kaas-kubernetes-3af5ae538cf411e9a6c7fa163e5a4837
    # Common data among all chart groups
    openstack:
            #      repo: osh
      version: stein
            #    infra:
            #      repo: osh-infra
  # features that would enable coordinated changes to values of several charts
  features:
    services:
     - block-storage
     - compute
     - identity
     - dashboard
     - image
     - ingress
     - mariadb
     - memcached
     - networking
     - orchestration
     - rabbitmq
#    messaging:
#      dedicated_rabbitmq:
#        enabled: True
    keystone:
      iam:
        enabled: True
    glance:
      direct_upload: False
      backend: ceph
    cinder:
      volume:
        backend: ceph
      backup:
        backend: ceph
    neutron:
      backend: ovs
    nova:
      image_backend: ceph
  # enabled services and their specific configuration
  services:
    ingress:
      ingress:
        values: {}
    memcached:
      memcached:
        values: {}
    mariadb:
      mariadb:
        values: {}
    rabbitmq:
      rabbitmq:
        values: {}
    identity:
      keystone:
        values:
          conf:
            keystone:
              DEFAULT:
               mykey: myvalue
    image:
      glance:
        values: {}
    block-storage:
      cinder:
        values: {}
    networking:
      neutron:
        values: {}
    compute:
      nova:
        values: {}
    orchestration:
      heat:
        values: {}
    dashboard:
      horizon:
        values: {}
