apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: openstackdeployments.lcm.mirantis.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: lcm.mirantis.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: openstackdeployments
    # singular name to be used as an alias on the CLI and for display
    singular: openstackdeployment
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: OpenStackDeployment
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - osdpl
    - osdpls
  additionalPrinterColumns:
    - name: Age
      type: string
      priority: 0
      JSONPath: .status.updated_at
      description: time since last change
    - name: Children
      type: string
      priority: 0
      JSONPath: .status.children
      description: The children pods created.
    - name: Message
      type: string
      priority: 0
      JSONPath: .status.message
      description: As returned from the handler (sometimes).
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
