---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osh-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      application: osh-operator
  template:
    metadata:
      labels:
        application: osh-operator
    spec:
      serviceAccountName: osh-operator-account
      containers:
      - name: osh-controller
        # image: pshchelo/osh-operator:latest
        image: localhost:32000/osh-operator:registry
        imagePullPolicy: Always
        command: ['kopf', 'run', '-m', 'osh_operator.main']
...
