apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeployment
metadata:
  name: osh-dev
  labels: {}
  annotations: {}
spec:
  # base set of values to base on
  base: null
  # common values to pass into all charts and services
  common:
    charts:
      repositories:
      - name: oscore
        url: "https://artifactory.mcp.mirantis.net/artifactory/helm-dev-virtual/"
      version:
    images:
      repo:
    openstack:
      version: stein
      values: {}
    infra:
      values: {}
  # features that would enable coordinated changes to values of several charts
  features:
    keystone:
      iam:
        enabled: True
    glance:
      direct_upload: False
      backend: ceph
    cinder:
      volume:
        backend: ceph
      backup:
        backend: radosgw
    neutron:
      backend: ovs
    nova:
      image_backend: ceph
  # enabled services and their specific configuration
  services:
    ingress:
      enabled: True
      chart:
        repo: ""
        version: ""
    memcached:
      enabled: True
    mariadb:
      enabled: True
      chart:
        repo: ""
        version: ""
      values: {}
    rabbitmq:
      enabled: True
      chart:
        repo: ""
        version: ""
      values: {}
