---
- name: Install k0s controllers
  hosts: controllers
  gather_facts: true
  become: true
  remote_user: ubuntu
  pre_tasks:
    - name: Set facts
      set_fact:
        k0s_cluster_nodes:
          initial_controller: "{{ groups.k0s_controllers[0] }}"
          controllers: []
          workers: []
  roles:
    - role: bodsch.k0s
      tags:
        - k0s_prepare
        - k0s_download
        - k0s_install
        - k0s_configure
        - k0s_initial_controller
        - k0s_controller
        - k0s_service
        - k0s_finalize
