{%- from 'macros/connections.j2' import to_child_object %}
mariadb:
  StatefulSet:
    mariadb-server:
      hash_fields: []
      images: []
      manifest: ''
      ports:
        - protocol: TCP
          port: 3306
          name: mysql
        - protocol: TCP
          port: 9104
          name: metrics
        - protocol: TCP
          port: 4567
          name: wsrep
        - protocol: TCP
          port: 4568
          name: ist
        - protocol: TCP
          port: 4444
          name: sst
      pod_labels:
        application: mariadb
        component: server
      connections:
        egress:
          - {{ to_child_object("database", "mariadb", "StatefulSet", "mariadb-server", ["mysql", "wsrep", "ist", "sst"]) | indent(12)}}
  Job:
    exporter-create-sql-user:
      hash_fields: []
      images:
      - prometheus_create_mysql_user
      manifest: ''
    openstack-mariadb-cluster-wait:
      hash_fields: []
      images:
      - mariadb_scripted_test
      manifest: job_cluster_wait
