{%- from 'macros/connections.j2' import to_child_object %}
ingress:
  DaemonSet:
    ingress:
      connections:
        egress:
          - {{ to_child_object("orchestration", "heat", "Deployment", "heat-api", ["http"]) | indent(12)}}
          - {{ to_child_object("orchestration", "heat", "Deployment", "heat-cfn", ["http"]) | indent(12)}}
          - {{ to_child_object("identity", "keystone", "Deployment", "keystone-api", ["ks-pub"]) | indent(12)}}
          - {{ to_child_object("compute", "nova", "Deployment", "nova-api-metadata", ["n-metadata"]) | indent(12)}}
          - {{ to_child_object("compute", "nova", "Deployment", "nova-novncproxy", ["n-novnc"]) | indent(12)}}
          - {{ to_child_object("compute", "nova", "Deployment", "nova-api-osapi", ["n-api"]) | indent(12)}}
      hash_fields: []
      images:
      - ingress
      - ingress_module_init
      - ingress_tls_proxy
      manifest: deployment_ingress
      pod_labels:
        application: ingress
        component: server
  Deployment:
    ingress-error-pages:
      hash_fields: []
      images:
      - error_pages
      manifest: deployment_error
      pod_labels:
        application: ingress
        component: error-pages
