apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: openstackdeployments.lcm.mirantis.com
  annotations:
    "helm.sh/hook": crd-install
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: lcm.mirantis.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: openstackdeployments
    # singular name to be used as an alias on the CLI and for display
    singular: openstackdeployment
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: OpenStackDeployment
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - osdpl
    categories:
      - all
  additionalPrinterColumns:
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: Deployed
      type: boolean
      JSONPath: .status.deployed
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            openstack_version:
              description: version of OpenStack to deploy
              type: string
              enum:
                - stein
            profile:
              description: profile to deploy
              type: string
              enum:
                - base
            domain_name:
              type: string
            common:
              type: object
              properties:
                charts:
                  type: object
                  description: settings passed to every helm chart
                  properties:
                    releases:
                      type: object
                      properties:
                        values:
                          type: object
                    repositories:
                      type: array
                      description: list of helm chart repositories
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: symbolic name to reference this repo
                          url:
                            type: string
                            description: helm charts repo url
                        required:
                          - name
                          - url
                    values:
                      type: object
                infra:
                  type: object
                openstack:
                  type: object
                  properties:
                    repo:
                      type: string
            features:
              type: object
              required:
                - services
                - keystone
              properties:
                messaging:
                  type: object
                  properties:
                    dedicated_rabbitmq:
                      type: object
                      properties:
                        enabled:
                          description: >
                            enable deployment of each openstack service
                            with dedicated instance of rabbitmq
                            for intra-service communications
                          type: boolean
                ssl:
                  type: object
                  properties:
                    public_endpoints:
                      type: object
                      properties:
                        enabled:
                          description: >
                            enable ssl on public endpoints
                          type: boolean
                        ca_cert:
                          description: >
                            CA certificate
                          type: string
                        api_cert:
                          description: >
                            API server certificate
                          type: string
                        api_key:
                          description: >
                            API server private key
                          type: string
                services:
                  type: array
                  description: List of enabled openstack and auxiliary services
                  items:
                    type: string
                    enum:
                      - block-storage
                      - compute
                      - identity
                      - dashboard
                      - image
                      - ingress
                      - mariadb
                      - memcached
                      - networking
                      - orchestration
                      - object-storage
                      - rabbitmq
                      - tempest
                      - load-balancer
                      - dns
                keystone:
                  type: object
                  required:
                    - users
                  properties:
                    users:
                      type: object
                      required:
                        - admin
                      properties:
                        admin:
                          type: object
                          required:
                          - username
                          - password
                          properties:
                            username:
                              description: >
                                Username for admin of Openstack deployment
                              type: string
                            password:
                              description: >
                                Password for admin of Openstack deployment
                              type: string
                    keycloak:
                      type: object
                      properties:
                        enabled:
                          description: Trigger to enable keycloak integration
                          type: boolean
                        url:
                          type: string
                          description: Url for keycloak
                        oidc:
                          type: array
                          items:
                            type: object
                            properties:
                              OIDCProviderMetadataURL:
                                type: string
                                description: Override for URL where OpenID Connect Provider metadata can be found
                              OIDCRedirectURI:
                                type: array
                                description: The redirect_uri for this OpenID Connect client
                                items:
                                  type: string
                neutron:
                  type: object
                  properties:
                    backend:
                      type: string
                      description: Neutron backend
                      enum:
                        - ovs
                    external_networks:
                      type: array
                      items:
                        type: object
                        required:
                          - physnet
                          - bridge
                          - network_types
                        properties:
                          physnet:
                            type: string
                            description: Neutron physnet name
                          interface:
                            type: string
                            description: Physical interface mapped with physnet
                          bridge:
                            type: string
                            description: OVS bridge name to map with physnet.
                          network_types:
                            type: array
                            description: Network types allowed on particular physnet
                            items:
                              type: string
                              enum:
                                - flat
                                - vlan
                          vlan_ranges:
                            type: string
                            nullable: true
                            description: Range of vlans allowed on physnet
                          mtu:
                            type: integer
                            nullable: true
                stacklight:
                  type: object
                  properties:
                    enabled:
                      description: >
                        enable StackLight operations support system
                      type: boolean
            services:
              type: object
          required:
            - openstack_version
            - profile
            - domain_name
