---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: osh-system
  name: osh-operator-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: osh-operator-role-cluster
rules:

  # NOTE(pas-ha) needed for multi-instance, including dev override
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]
  - apiGroups: [zalando.org]
    resources: [clusterkopfpeerings]
    verbs: [list, get, watch, patch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [lcm.mirantis.com]
    resources: [openstackdeployments]
    verbs: [list, get, watch]
  - apiGroups: [lcm.mirantis.com]
    resources: [helmbundles]
    verbs: [list, get, watch]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: "{{ .Values.osdpl.namespace }}"
  name: "osh-operator-role-{{ .Values.osdpl.namespace }}"
rules:

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  # Application: read secret with keystone creds
  - apiGroups: [""]
    resources: [secrets]
    verbs: [list, get, watch, patch]
  # NOTE(pas-ha) needed for multi-instance, including dev override
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [kopfpeerings]
    verbs: [list, get, watch, patch]

  # Application: manage ceph access data(secrets,configmaps)
  - apiGroups: [""]
    resources: [secrets,configmaps]
    verbs: [list, get, create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [lcm.mirantis.com]
    resources: [openstackdeployments]
    verbs: [list, get, watch, patch]

  # Application: resources we produce and manipulate.
  - apiGroups: [lcm.mirantis.com]
    resources: [helmbundles]
    verbs: [list, get, watch, create, update, patch, delete]

  # Manage child reousrces only list and delete grants
  - apiGroups: [extensions, apps, batch]
    resources: [deployments, jobs]
    verbs: [list, get, delete]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: "openstack-ceph-shared"
  name: "osh-operator-role-openstack-ceph-shared"
rules:

  # Application: read ceph access data from shared namespace.
  - apiGroups: [""]
    resources: [secrets,configmaps]
    verbs: [list, get, create, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: osh-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osh-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: osh-operator-account
    namespace: osh-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: "{{ .Values.osdpl.namespace }}"
  name: "osh-operator-rolebinding-{{ .Values.osdpl.namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "osh-operator-role-{{ .Values.osdpl.namespace }}"
subjects:
  - kind: ServiceAccount
    name: osh-operator-account
    namespace: osh-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: "openstack-ceph-shared"
  name: "osh-operator-rolebinding-openstack-ceph-shared"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "osh-operator-role-openstack-ceph-shared"
subjects:
  - kind: ServiceAccount
    name: osh-operator-account
    namespace: osh-system
---
apiVersion: zalando.org/v1
kind: KopfPeering
metadata:
  namespace: "{{ .Values.osdpl.namespace }}"
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osh-operator.fullname" . }}
  namespace: osh-system
  labels:
    app.kubernetes.io/name: {{ include "osh-operator.name" . }}
    helm.sh/chart: {{ include "osh-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "osh-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "osh-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: osh-operator-account
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
            - run
            - '-m'
            - osh_operator.openstackdeployment
            - '-m'
            - osh_operator.helmbundle
            - '-m'
            - osh_operator.secrets
            - '-n'
            - openstack
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
