# Default values for openstack-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker-kaas-local.artifactory.mirantis.com/mcp/openstack-controller
  tag: 0.1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

kopf:
  enabled: true

osdpl:
  namespace: openstack


helmbundle:
  # unless we deploy it via kaas management cluster
  enabled: false
  image:
    repository: docker-prod-local.artifactory.mirantis.com/mirantis/kubernetes/lcm/lcm-controller
    tag: latest
    pullPolicy: IfNotPresent
  tiller:
    image:
      repository: gcr.io/kubernetes-helm/tiller
      tag: v2.13.1
      pullPolicy: IfNotPresent

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
