# Default values for openstack-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  dockerBaseUrl: docker-kaas-local.artifactory.mirantis.com
  helmBaseUrl: https://artifactory.mirantis.com/binary-kaas-local

replicaCount: 1

image:
  repository: openstack
  name: openstack-controller
  tag: 0.1.6
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

kopf:
  enabled: true

osdpl:
  namespace: openstack
  cephSharedNamespace: openstack-ceph-shared

tf:
  createSharedNamespace: true
  sharedNamespace: openstack-tf-shared

helmbundle:
  # unless we deploy it via kaas management cluster
  enabled: false
  image:
    repository: lcm
    name: lcm-controller
    tag: v0.2.0-43
    pullPolicy: IfNotPresent
  tiller:
    image:
      repository: lcm/helm
      name: tiller
      tag: v2.15.2-1
      pullPolicy: IfNotPresent

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
