#connection_recycle_time is set to 300sec in order not to hit into conntrack timeouts (PRODX-1179, PRODX-1170)
services:
  database:
    mariadb:
      values:
        conf:
          ingress_conf:
            proxy-buffer-size: "20m"
            proxy-connect-timeout: "600"
  identity:
    keystone:
      values:
        pod:
          replicas:
            api: 30
        conf:
          keystone:
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  image:
    glance:
      values:
        pod:
          replicas:
            api: 3
            registry: 3
        conf:
          glance:
            DEFAULT:
              workers: 8
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  compute:
    nova:
      values:
        pod:
          replicas:
            api_metadata: 3
            osapi: 15
            conductor: 3
            consoleauth: 3
            scheduler: 3
            novncproxy: 3
            placement: 4
        conf:
          nova:
            DEFAULT:
              cpu_allocation_ratio: 8.0
              ram_allocation_ratio: 1.1
              disk_allocation_ratio: 1.6
              metadata_workers: 8
              osapi_compute_workers: 8
              block_device_allocate_retries: 600
              block_device_allocate_retries_interval: 10
              report_interval: 60
              service_down_time: 180
              rpc_response_timeout: 30
            api_database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            cell0_database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            placement_database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            conductor:
              workers: 8
            scheduler:
              workers: 1
            neutron:
              timeout: 300
            filter_scheduler:
              host_subset_size: 30
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  networking:
    neutron:
      values:
        pod:
          replicas:
            server: 12
        conf:
          neutron:
            DEFAULT:
              dhcp_lease_duration: 600
              rpc_workers: 16
              api_workers: 16
              rpc_state_report_workers: 4
              agent_down_time: 30
              max_l3_agents_per_router: 0
              executor_thread_pool_size: 70
            agent:
              report_interval: 10
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 70
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  block-storage:
    cinder:
      values:
        pod:
          replicas:
            api: 4
            scheduler: 3
            volume: 6
        conf:
          cinder:
            DEFAULT:
              rpc_response_timeout: 3600
              osapi_volume_workers: 4
              backup_workers: 4
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  orchestration:
    heat:
      values:
        pod:
          replicas:
            cfn: 3
            api: 3
            engine: 15
        conf:
          heat:
            DEFAULT:
              rpc_response_timeout: 600
              num_engine_workers: 6
              max_resources_per_stack: '20000'
              max_template_size: '5440000'
              max_json_body_size: '10880000'
            heat_api:
              workers: 4
            heat_api_cfn:
              workers: 1
            heat_api_cloudwatch:
              workers: 4
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
  load-balancer:
    octavia:
      values:
        pod:
          replicas:
            api: 3
        conf:
          octavia:
            database:
              max_pool_size: 10
              max_retries: -1
              max_overflow: 30
              connection_recycle_time: 300
            controller_worker:
              amp_active_retries: 100
              amp_active_wait_sec: 2
              workers: 8
            haproxy_amphora:
              connection_max_retries: 1500
              connection_retry_interval: 1
              rest_request_conn_timeout: 10
              rest_request_read_timeout: 120
            task_flow:
              engine: parallel
              max_workers: 64
            house_keeping:
              amphora_expiry_age: 3600
              load_balancer_expiry_age: 3600
            oslo_messaging_rabbit:
              rabbit_qos_prefetch_count: 64
