#apiVersion: lcm.mirantis.com/v1alpha1
#kind: HelmBundle

spec:
  available_releases:
    - "ingress-openstack"
  releases:
  - name: ingress-openstack
    chart: {{spec.common.infra.repo}}/ingress
    values:
      deployment:
        type: DaemonSet
      labels:
        server:
          node_selector_key: kubernetes.io/os
          node_selector_value: linux
      network:
        service:
          type: LoadBalancer
          externalTrafficPolicy: Local
      images:
        tags:
{%- for image in [
    "ingress",
    "ingress_routed_vip",
    "error_pages",
    "image_repo_sync",
    "keepalived",
    "ingress_module_init",
    "entrypoint",
    "dep_check",] %}
        {%- if image in images %}
          {{ image }}: {{ images[image] }}
        {%- endif %}
{%- endfor %}
      conf:
        ingress:
          # TODO: allow only stacklight pods
          nginx-status-ipv4-whitelist: "0.0.0.0/0"
          # NOTE(vsaienko) jwt tokens might be too big
          client-header-buffer-size: 10k
          large-client-header-buffers: 4 16k
      pod:
        probes:
          server:
            ingress:
              readiness:
                enabled: true
                params: {}
              liveness:
                enabled: true
                params:
                  initialDelaySeconds: 10
                  timeoutSeconds: 5
      manifests:
        network_policy: false
      endpoints:
        cluster_domain_suffix: {{ spec.internal_domain_name }}
