#apiVersion: lcm.mirantis.com/v1alpha1
#kind: HelmBundle

spec:
  releases:
  - name: ingress-openstack
    chart: {{spec.common.infra.repo}}/ingress
    values:
      images:
        tags:
{%- for image in [
    "ingress",
    "ingress_routed_vip",
    "error_pages",
    "image_repo_sync",
    "keepalived",
    "ingress_module_init",
    "entrypoint",
    "dep_check",] %}
        {%- if image in images %}
          {{ image }}: {{ images[image] }}
        {%- endif %}
{%- endfor %}
      manifests:
        network_policy: false
      endpoints:
        cluster_domain_suffix: {{ spec.domain_name }}
