common:
  charts:
    releases:
      namespace: openstack
  openstack:
    values:
      pod:
        # TODO(vsaienko): move resource count to dedicated `size` layer
        replicas:
          api: 3
          server: 3
features:
  glance:
    backend: ceph
  cinder:
    volume:
      backend: ceph
    backup:
      backend: ceph
  neutron:
    backend: ovs
  messaging:
    dedicated_rabbitmq:
      enabled: true
  database:
    local_volumes:
      enabled: true
  ssl:
    public_endpoints:
      enabled: true
  stacklight:
    enabled: true
    user:
      password: stacklight
services:
  image:
    glance:
      values:
        bootstrap:
          enabled: true
          ks_user: admin
          structured:
            images:
              cirros:
                container_format: bare
                image_file: cirros-0.4.0-x86_64-disk.img
                image_type: qcow2
                min_disk: 1
                name: Cirros-4.0
                private: false
                properties:
                  os_distro: cirros
                source_url: https://artifactory.mcp.mirantis.net/artifactory/test-images/
              fedora:
                container_format: bare
                image_file: Fedora-Cloud-Base-27-1.6.x86_64.qcow2
                image_type: qcow2
                min_disk: 1
                name: Fedora-27-1.6
                private: false
                properties:
                  os_distro: fedora
                source_url: https://artifactory.mcp.mirantis.net/artifactory/test-images/
  compute:
    nova:
      values:
        bootstrap:
          structured:
            flavors:
              options:
                m1.extra_tiny_test:
                  disk: 5
                  name: m1.extra_tiny_test
                  ram: 256
                  vcpus: 1
                m1.tiny_test:
                  disk: 5
                  name: m1.tiny_test
                  ram: 512
                  vcpus: 1
  tempest:
    tempest:
      values:
        bootstrap:
          enabled: true
          script: |
            openstack network show heat-net || openstack network create heat-net
            openstack subnet show heat-subnet || openstack subnet create heat-subnet \
              --dhcp --subnet-range 10.20.30.0/24 \
              --allocation-pool start=10.20.30.10,end=10.20.30.254 \
              --gateway 10.20.30.1 \
              --network heat-net
            openstack router show heat-router || openstack router create heat-router
            openstack router add subnet heat-router heat-subnet
            openstack router set --external-gateway public heat-router
            openstack role create --or-show "key-manager:service-admin"
            openstack role create --or-show creator
        dependencies:
          static:
            run_tests:
              jobs:
                - tempest-ks-user
                - tempest-bootstrap
        conf:
          convert_to_uuid:
            network:
              public_network_id: public
            compute:
              image_ref: Cirros-4.0
              image_ref_alt: Cirros-4.0
              flavor_ref:  m1.extra_tiny_test
              flavor_ref_alt: m1.tiny_test
          blacklist:
            - (?:tempest\.fake\.test)
            - (?:heat_tempest_plugin\.)
            - (?:designate_tempest_plugin.tests.scenario.v2.test_recordsets.RecordsetsTest\.)
          script: |
            tempest run --config-file /etc/tempest/tempest.conf -w 4 --smoke --blacklist-file  /etc/tempest/test-blacklist
          tempest:
            dashboard:
              disable_ssl_certificate_validation: true
            validation:
              image_ssh_password: gocubsgo
              image_ssh_user: cirros
            network:
              shared_physical_network: false
              floating_network_name: public
            #TODO: Will be automated soon in filters.
            volume:
              storage_protocol: ceph
            #TODO: Will be automated soon in filters.
            network-feature-enabled:
              api_extensions:
                - default-subnetpools
                - network-ip-availability
                - network_availability_zone
                - auto-allocated-topology
                - ext-gw-mode
                - binding
                - agent
                - subnet_allocation
                - l3_agent_scheduler
                - tag
                - external-net
                - flavors
                - net-mtu
                - availability_zone
                - quotas
                - l3-ha
                - provider
                - multi-provider
                - address-scope
                - extraroute
                - subnet-service-types
                - standard-attr-timestamp
                - service-type
                - l3-flavors
                - port-security
                - extra_dhcp_opt
                - standard-attr-revisions
                - pagination
                - sorting
                - security-group
                - dhcp_agent_scheduler
                - router_availability_zone
                - rbac-policies
                - standard-attr-description
                - router
                - allowed-address-pairs
                - project-id
                - dvr
                - filter-validation
        manifests:
          job_bootstrap: true
