---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: osh-system
  name: openstack-controller-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: openstack-controller-role-cluster
rules:

  # NOTE(pas-ha) needed for multi-instance, including dev override
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]
  - apiGroups: [zalando.org]
    resources: [clusterkopfpeerings]
    verbs: [list, get, watch, patch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [lcm.mirantis.com]
    resources: [openstackdeployments]
    verbs: [list, get, watch]
  - apiGroups: [lcm.mirantis.com]
    resources: [helmbundles]
    verbs: [list, get, watch]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: openstack
  name: openstack-controller-role-openstack
rules:

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  # Application: read secret with keystone creds
  - apiGroups: [""]
    resources: [secrets]
    verbs: [list, get, watch, patch]
  # NOTE(pas-ha) needed for multi-instance, including dev override
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [kopfpeerings]
    verbs: [list, get, watch, patch]

  # Application: manage ceph access data(secrets,configmaps)
  - apiGroups: [""]
    resources: [secrets,configmaps]
    verbs: [list, get, create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [lcm.mirantis.com]
    resources: [openstackdeployments]
    verbs: [list, get, watch, patch]

  # Application: resources we produce and manipulate.
  - apiGroups: [lcm.mirantis.com]
    resources: [helmbundles]
    verbs: [list, get, watch, create, update, patch, delete]

    # Manage child reousrces only list and delete grants
  - apiGroups: [extensions, apps, batch]
    resources: [deployments, jobs]
    verbs: [list, get, delete]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: "openstack-ceph-shared"
  name: "openstack-controller-role-openstack-ceph-shared"
rules:

  # Application: read ceph access data from shared namespace.
  - apiGroups: [""]
    resources: [secrets,configmaps]
    verbs: [list, get, patch, create, update]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: openstack-controller-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openstack-controller-role-cluster
subjects:
  - kind: ServiceAccount
    name: openstack-controller-account
    namespace: osh-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: openstack
  name: openstack-controller-rolebinding-openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstack-controller-role-openstack
subjects:
  - kind: ServiceAccount
    name: openstack-controller-account
    namespace: osh-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: "openstack-ceph-shared"
  name: "openstack-controller-rolebinding-openstack-ceph-shared"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "openstack-controller-role-openstack-ceph-shared"
subjects:
  - kind: ServiceAccount
    name: openstack-controller-account
    namespace: osh-system
---
apiVersion: zalando.org/v1
kind: KopfPeering
metadata:
  namespace: openstack
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openstack-controller
  namespace: osh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      application: openstack-controller
  template:
    metadata:
      labels:
        application: openstack-controller
    spec:
      serviceAccountName: openstack-controller-account
      containers:
      - name: osh-controller
        # image: pshchelo/openstack-controller:latest
        image: docker-prod-local.docker.mirantis.net/mcp/openstack-controller:nightly
        imagePullPolicy: Always
        command:
          - kopf
          - run
          - '-m'
          - openstack_controller.openstackdeployment
          - '-m'
          - openstack_controller.helmbundle
          - '-n'
          - openstack
...
