---
apiVersion: v1
kind: Namespace
metadata:
  name: osh-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: osh-system
  name: osh-operator-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: osh-operator-role-cluster
rules:

  # NOTE(pas-ha) do not need it for now, running single instance
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]
  - apiGroups: [zalando.org]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [lcm.mirantis.com]
    resources: [openstackdeployments]
    verbs: [create, get, list, watch, patch, delete]

  - apiGroups: [lcm.mirantis.com]
    resources: [helmbundles]
    verbs: [create, get, list, watch, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: osh-system
  name: osh-operator-role-namespaced
rules:

  # NOTE(pas-ha) do not need it for now, running single instance
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [lcm.mirantis.com]
    resources: [openstackdeployments]
    verbs: [create, get, list, watch, patch, delete]

  # Application: other resources it produces and manipulates.
  - apiGroups: [lcm.mirantis.com]
    resources: [helmbundles]
    verbs: [create, get, list, watch, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: osh-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osh-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: osh-operator-account
    namespace: osh-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: osh-system
  name: osh-operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: osh-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: osh-operator-account
...
