{{- if .Values.admission.enabled -}}
{{- $cn1 := printf "%s-admission.osh-system.svc" (include "openstack-controller.name" .) }}
{{- $cn2 := printf "%s-admission.osh-system.svc.%s" (include "openstack-controller.name" .) (.Values.admission.cluster_domain_suffix) }}
{{- $cabundle := genCA $cn1 3650 }}
{{- $client := genSignedCert $cn1  nil (list $cn1 $cn2) 365 $cabundle }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openstack-controller.name" . }}-admission
  namespace: osh-system
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "openstack-controller.name" . }}-admission
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openstack-controller.name" . }}-admission-tls
  namespace: osh-system
data:
{{- if empty .Values.admission.tls }}
  oac.crt: {{ $client.Cert  | b64enc }}
  oac.key: {{ $client.Key  | b64enc }}
{{- else }}
  oac.crt: {{ .Values.admission.tls.crt | b64enc }}
  oac.key: {{ .Values.admission.tls.key | b64enc }}
{{- end }}
type: Opaque
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "openstack-controller.name" . }}-admission
webhooks:
  - name: {{ include "openstack-controller.name" . }}-admission.osh-system.svc
    clientConfig:
      service:
        name: {{ include "openstack-controller.name" . }}-admission
        namespace: osh-system
        path: "/validate"
{{- if empty .Values.admission.tls }}
      caBundle: {{ $cabundle.Cert | b64enc }}
{{- else }}
      caBundle: {{ .Values.admission.tls.ca | b64enc }}
{{- end }}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["lcm.mirantis.com"]
        apiVersions: ["v1alpha1"]
        resources: ["openstackdeployments"]
        scope: "Namespaced"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openstack-controller.name" . }}-admission
  namespace: osh-system
spec:
  replicas: {{ .Values.admission.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "openstack-controller.name" . }}-admission
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "openstack-controller.name" . }}-admission
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - uwsgi
            - /opt/operator/uwsgi.ini
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/opt/operator/certs"
              name: {{ include "openstack-controller.name" . }}-admission-tls
              readOnly: true
      volumes:
        - name: {{ include "openstack-controller.name" . }}-admission-tls
          secret:
            secretName: {{ include "openstack-controller.name" . }}-admission-tls
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
