{{- if .Values.exporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: {{ include "openstack-controller.name" . }}-exporter
    helm.sh/chart: {{ include "openstack-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    application: openstack-controller
    component: exporter
  name: openstack-controller-exporter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: {{ .Values.exporter.settings.raw.OSCTL_EXPORTER_BIND_PORT }}
  selector:
    application: openstack-controller
    component: exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
{{- end }}
