apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: openstackdeployments.lcm.mirantis.com
  annotations:
    "helm.sh/hook": crd-install
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: lcm.mirantis.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: openstackdeployments
    # singular name to be used as an alias on the CLI and for display
    singular: openstackdeployment
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: OpenStackDeployment
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - osdpl
    categories:
      - all
  additionalPrinterColumns:
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: Deployed
      type: boolean
      JSONPath: .status.deployed
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            artifacts:
              type: object
              properties:
                images_base_url:
                  type: string
                  description: "base URL for docker images"
                charts_base_url:
                  type: string
                  description: "base URL for repo with helm charts."
            openstack_version:
              description: version of OpenStack to deploy
              type: string
              enum:
                - queens # not supported, only for migration
                - rocky # not supported, only for migration
                - stein
                - master
            profile:
              description: profile to deploy
              type: string
              enum:
                - compute
            size:
              description: timeout and sizing parameters
              type: string
              enum:
                - tiny
                - small
                - medium
            public_domain_name:
              type: string
              description: domain name used for public endpoints
            internal_domain_name:
              type: string
              description: internal k8s domain name
            common:
              type: object
              properties:
                charts:
                  type: object
                  description: settings passed to every helm chart
                  properties:
                    releases:
                      type: object
                      properties:
                        values:
                          type: object
                    repositories:
                      type: array
                      description: list of helm chart repositories
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: symbolic name to reference this repo
                          url:
                            type: string
                            description: helm charts repo url
                        required:
                          - name
                          - url
                    values:
                      type: object
                infra:
                  type: object
                openstack:
                  type: object
                  properties:
                    repo:
                      type: string
            features:
              type: object
              required:
                - services
                - keystone
                - neutron
                - nova
              properties:
                messaging:
                  type: object
                  properties:
                    dedicated_rabbitmq:
                      type: object
                      properties:
                        enabled:
                          description: >
                            enable deployment of each openstack service
                            with dedicated instance of rabbitmq
                            for intra-service communications
                          type: boolean
                ssl:
                  type: object
                  properties:
                    public_endpoints:
                      type: object
                      properties:
                        enabled:
                          description: >
                            enable ssl on public endpoints
                          type: boolean
                        ca_cert:
                          description: >
                            CA certificate
                          type: string
                        api_cert:
                          description: >
                            API server certificate
                          type: string
                        api_key:
                          description: >
                            API server private key
                          type: string
                barbican:
                  type: object
                  properties:
                    backend:
                      type: object
                      properties:
                        simple_crypto:
                          type: object
                          properties:
                            enabled:
                              description: >
                                Indicates if simple_crypto backend is enabled
                              type: boolean
                            kek:
                              description: >
                                A 32-byte value which is base64 encoded, needed for simple_crypto backend
                              type: string
                services:
                  type: array
                  description: List of enabled openstack and auxiliary services
                  items:
                    type: string
                    enum:
                      - block-storage
                      - compute
                      - identity
                      - dashboard
                      - image
                      - ingress
                      - database
                      - memcached
                      - networking
                      - orchestration
                      - object-storage
                      - messaging
                      - tempest
                      - load-balancer
                      - dns
                      - key-manager
                nova:
                  type: object
                  required:
                    - live_migration_interface
                  properties:
                    live_migration_interface:
                      type: string
                      description: "Physical interface used for live migration."
                    images:
                      type: object
                      properties:
                        backend:
                          description: >
                            backend for nova images can be ceph or local
                          type: string
                          enum:
                            - local
                            - ceph
                keystone:
                  type: object
                  properties:
                    users:
                      type: object
                      properties:
                        admin:
                          type: object
                          properties:
                            region_name:
                              description: >
                                OpenStack region name
                              type: string
                            project_name:
                              description: >
                                Project name for admin of OpenStack deployment
                              type: string
                            user_domain_name:
                              description: >
                                Domain name for admin of OpenStack deployment
                              type: string
                            project_domain_name:
                              description: >
                                Project domain name for admin of OpenStack deployment
                              type: string
                            default_domain_id:
                              description: >
                                Domain ID for admin of OpenStack deployment
                              type: string
                    keycloak:
                      type: object
                      properties:
                        enabled:
                          description: Trigger to enable keycloak integration
                          type: boolean
                        url:
                          type: string
                          description: Url for keycloak
                        oidc:
                          type: object
                          items:
                            type: object
                            properties:
                              OIDCProviderMetadataURL:
                                type: string
                                description: Override for URL where OpenID Connect Provider metadata can be found
                              OIDCRedirectURI:
                                type: array
                                description: The redirect_uri for this OpenID Connect client
                                items:
                                  type: string
                              OIDCSSLValidateServer:
                                type: boolean
                                description: Require a valid SSL server certificate when communicating with the OP
                neutron:
                  type: object
                  required:
                    - tunnel_interface
                  properties:
                    tunnel_interface:
                      type: string
                      description: "Physical interface used for tunnel traffic"
                    backend:
                      type: string
                      description: Neutron backend
                      enum:
                        - ovs
                    external_networks:
                      type: array
                      items:
                        type: object
                        required:
                          - physnet
                          - bridge
                          - network_types
                        properties:
                          physnet:
                            type: string
                            description: Neutron physnet name
                          interface:
                            type: string
                            description: Physical interface mapped with physnet
                          bridge:
                            type: string
                            description: OVS bridge name to map with physnet.
                          network_types:
                            type: array
                            description: Network types allowed on particular physnet
                            items:
                              type: string
                              enum:
                                - flat
                                - vlan
                          vlan_ranges:
                            type: string
                            nullable: true
                            description: Range of vlans allowed on physnet
                          mtu:
                            type: integer
                            nullable: true
                stacklight:
                  type: object
                  required:
                    - user
                  properties:
                    enabled:
                      description: >
                        enable StackLight operations support system
                      type: boolean
                    user:
                      type: object
                      required:
                        - password
                      properties:
                        username:
                          type: string
                          description: >
                            Rabbitmq username to access notifications.
                        password:
                          type: string
                          description: >
                            Rabbitmq password to access notifications.
                logging:
                  type: object
                  properties:
                    cinder: &logging_level
                      type: object
                      properties:
                        level:
                          type: string
                          description: Service logging level
                          enum:
                            - DEBUG
                            - INFO
                            - WARNING
                            - ERROR
                            - CRITICAL
                    designate:
                      <<: *logging_level
                    glance:
                      <<: *logging_level
                    heat:
                      <<: *logging_level
                    keystone:
                      <<: *logging_level
                    neutron:
                      <<: *logging_level
                    nova:
                      <<: *logging_level
                    octavia:
                      <<: *logging_level
            services:
              type: object
          required:
            - openstack_version
            - profile
            - size
            - public_domain_name
            - internal_domain_name
