apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: openstackdeployments.lcm.mirantis.com
  annotations:
    "helm.sh/hook": crd-install
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: lcm.mirantis.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: openstackdeployments
    # singular name to be used as an alias on the CLI and for display
    singular: openstackdeployment
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: OpenStackDeployment
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - osdpl
    categories:
      - all
  additionalPrinterColumns:
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: Deployed
      type: boolean
      JSONPath: .status.deployed
    - name: Draft
      type: boolean
      JSONPath: .spec.draft
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            draft:
              type: boolean
              description: trigger to process osdpl resource
            artifacts:
              type: object
              properties:
                images_base_url:
                  type: string
                  description: "base URL for docker images"
                binary_base_url:
                  type: string
                  description: "base URL for repo with helm charts & other binaries"
            openstack_version:
              description: version of OpenStack to deploy
              type: string
              enum:
                - queens # not supported, only for migration
                - rocky # not supported, only for migration
                - stein # not supported, only for migration
                - train
                - ussuri # under development
                - master # not supported, only for example
            profile:
              description: profile to deploy
              type: string
              enum:
                - compute
                - compute-tf
            size:
              description: timeout and sizing parameters
              type: string
              enum:
                - tiny
                - small
                - medium
            public_domain_name:
              type: string
              description: domain name used for public endpoints
            internal_domain_name:
              type: string
              description: internal k8s domain name
            common:
              type: object
              properties:
                charts:
                  type: object
                  description: settings passed to every helm chart
                  properties:
                    releases:
                      type: object
                      properties:
                        values:
                          type: object
                    repositories:
                      type: array
                      description: list of helm chart repositories
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: symbolic name to reference this repo
                          url:
                            type: string
                            description: helm charts repo url
                        required:
                          - name
                          - url
                    values:
                      type: object
                infra:
                  type: object
                openstack:
                  type: object
                  properties:
                    repo:
                      type: string
            features:
              type: object
              required:
                - ssl
                - neutron
                - nova
              properties:
                ssl:
                  type: object
                  required:
                   - public_endpoints
                  properties:
                    public_endpoints:
                      type: object
                      required:
                        - ca_cert
                        - api_cert
                        - api_key
                      properties:
                        ca_cert:
                          description: >
                            CA certificate
                          type: string
                        api_cert:
                          description: >
                            API server certificate
                          type: string
                        api_key:
                          description: >
                            API server private key
                          type: string
                barbican:
                  type: object
                  properties:
                    backends:
                      type: object
                      properties:
                        vault:
                          type: object
                          properties:
                            enabled:
                              description: >
                                Indicates if simple_crypto backend is enabled
                              type: boolean
                            approle_role_id:
                              description: >
                                Specifies the app role ID
                              type: string
                            approle_secret_id:
                              description: >
                                 Specifies the secret ID created for the app role
                              type: string
                            vault_url:
                              description: >
                                URL of the Vault server
                              type: string
                            use_ssl:
                              description: >
                                Specifies whether to use SSL
                              type: boolean
                            ssl_ca_crt_file:
                              description: >
                                The path to CA cert file
                              type: string
                services:
                  type: array
                  description: List of enabled openstack and auxiliary services
                  items:
                    type: string
                    enum:
                      - block-storage
                      - compute
                      - identity
                      - dashboard
                      - image
                      - ingress
                      - database
                      - memcached
                      - networking
                      - orchestration
                      - object-storage
                      - messaging
                      - tempest
                      - load-balancer
                      - dns
                      - key-manager
                      - placement
                      - coordination
                      - dashboard-selenium
                nova:
                  type: object
                  required:
                    - live_migration_interface
                  properties:
                    live_migration_interface:
                      type: string
                      description: "Physical interface used for live migration."
                    images:
                      type: object
                      properties:
                        backend:
                          description: >
                            backend for nova images can be ceph or local
                          type: string
                          enum:
                            - local
                            - ceph
                keystone:
                  type: object
                  properties:
                    users:
                      type: object
                      properties:
                        admin:
                          type: object
                          properties:
                            region_name:
                              description: >
                                OpenStack region name
                              type: string
                            project_name:
                              description: >
                                Project name for admin of OpenStack deployment
                              type: string
                            user_domain_name:
                              description: >
                                Domain name for admin of OpenStack deployment
                              type: string
                            project_domain_name:
                              description: >
                                Project domain name for admin of OpenStack deployment
                              type: string
                            default_domain_id:
                              description: >
                                Domain ID for admin of OpenStack deployment
                              type: string
                    keycloak:
                      type: object
                      properties:
                        enabled:
                          description: Trigger to enable keycloak integration
                          type: boolean
                        url:
                          type: string
                          description: Url for keycloak
                        oidc:
                          type: object
                          items:
                            type: object
                            properties:
                              OIDCProviderMetadataURL:
                                type: string
                                description: Override for URL where OpenID Connect Provider metadata can be found
                              OIDCRedirectURI:
                                type: array
                                description: The redirect_uri for this OpenID Connect client
                                items:
                                  type: string
                              OIDCSSLValidateServer:
                                type: boolean
                                description: Require a valid SSL server certificate when communicating with the OP
                neutron:
                  type: object
                  required:
                    - tunnel_interface
                  properties:
                    tunnel_interface:
                      type: string
                      description: "Physical interface used for tunnel traffic"
                    dns_servers:
                      type: array
                      description: >
                        The list with the IP addresses of DNS servers reachable from Virtual Networks
                    backend:
                      type: string
                      description: Neutron backend
                      enum:
                        - ml2
                        - tungstenfabric
                    external_networks:
                      type: array
                      items:
                        type: object
                        required:
                          - physnet
                          - bridge
                          - network_types
                        properties:
                          physnet:
                            type: string
                            description: Neutron physnet name
                          interface:
                            type: string
                            description: Physical interface mapped with physnet
                          bridge:
                            type: string
                            description: OVS bridge name to map with physnet.
                          network_types:
                            type: array
                            description: Network types allowed on particular physnet
                            items:
                              type: string
                              enum:
                                - flat
                                - vlan
                                - vxlan
                                - gre
                                - local
                          vlan_ranges:
                            type: string
                            nullable: true
                            description: Range of vlans allowed on physnet
                          mtu:
                            type: integer
                            nullable: true
                    floating_network:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          description: >
                            enable floating network creation
                        name:
                          type: string
                          description: The name of floating network
                        physnet:
                          type: string
                          description: >
                            name of physical network to associate
                        subnet:
                          type: object
                          required:
                            - range
                            - pool_start
                            - pool_end
                            - gateway
                          properties:
                            name:
                              type: string
                              description: "The name of floating subnet"
                            range:
                              type: string
                              description: "IP address range ie: 1.2.3.0/24"
                            pool_start:
                              type: string
                              description: "start IP address ie: 1.2.3.100"
                            pool_end:
                              type: string
                              description: "end IP address ie: 1.2.3.200"
                            gateway:
                              type: string
                              description: "IP address of subnet gateway"
                        router:
                          type: object
                          properties:
                            name:
                              type: string
                              description: "The name of public router"
                octavia:
                  type: object
                  properties:
                    lb_network:
                      type: object
                      required:
                        - subnet
                      properties:
                        subnet:
                          type: object
                          required:
                            - range
                            - pool_start
                            - pool_end
                          properties:
                            range:
                              type: string
                              description: "IP address range ie: 1.2.3.0/24"
                            pool_start:
                              type: string
                              description: "start IP address ie: 1.2.3.100"
                            pool_end:
                              type: string
                              description: "end IP address ie: 1.2.3.200"
                stacklight:
                  type: object
                  required:
                    - user
                  properties:
                    enabled:
                      description: >
                        enable StackLight operations support system
                      type: boolean
                    user:
                      type: object
                      required:
                        - password
                      properties:
                        username:
                          type: string
                          description: >
                            Rabbitmq username to access notifications.
                        password:
                          type: string
                          description: >
                            Rabbitmq password to access notifications.
                logging:
                  type: object
                  properties:
                    cinder: &logging_level
                      type: object
                      properties:
                        level:
                          type: string
                          description: Service logging level
                          enum:
                            - DEBUG
                            - INFO
                            - WARNING
                            - ERROR
                            - CRITICAL
                    designate:
                      <<: *logging_level
                    glance:
                      <<: *logging_level
                    heat:
                      <<: *logging_level
                    keystone:
                      <<: *logging_level
                    neutron:
                      <<: *logging_level
                    nova:
                      <<: *logging_level
                    octavia:
                      <<: *logging_level
            services:
              type: object
            timeouts:
              type: object
              properties:
                applicaion_readiness:
                  type: object
                  properties:
                    nova: &application_readiness
                      type: objecet
                      properties:
                        timeout:
                          type: integer
                          description: Number of seconds to wait for application becomes ready.
                        delay:
                          type: integer
                          description: Number of seconds between readiness attempts.
                    neutron:
                      <<: *application_readiness
          required:
            - openstack_version
            - profile
            - size
            - public_domain_name
            - internal_domain_name
