apiVersion: v1
data:
kind: ConfigMap
data:
  logging.conf: |
{{ toYaml ( index .Values.osdpl "logging.conf" ) | indent 4}}
metadata:
  name: openstack-controller-etc
  namespace: {{ .Release.Namespace }}
