{{ if eq .Values.osdpl.namespace .Values.osdpl.settings.raw.OSCTL_REDIS_NAMESPACE }}
  {{ fail "Osdpl namespace and Redis namespace should be different!" }}
{{ end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: openstack-controller-account
# The openstack-controller-account requires cluster wide role to use privileged
# attributes (host bind mounts, host network, kernel capabilities) mostly on
# daemonsets.apps by way of helm operations.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
  name: openstack-controller-account:cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: openstack-controller-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openstack-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "openstack-controller.name" . }}
    helm.sh/chart: {{ include "openstack-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  # Make sure old operator gone to prevent that old version start
  # handling resume event.
  strategy:
   type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "openstack-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "openstack-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: openstack-controller-account
      securityContext:
        {{- toYaml .Values.osdpl.pod.controller.security_context | nindent 8 }}
      initContainers:
        - name: remove-default-finalizer
          command:
          - osctl-remove-default-finalizer
          env:
{{ tuple . | include "openstack-controller.common_env" | indent 12 }}
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.osdpl.pod.controller.remove_default_finalizer.security_context | nindent 12 }}
        - name: convert-credential-secrets
          command:
          - osctl-convert-credential-secrets
          env:
{{ tuple . | include "openstack-controller.common_env" | indent 12 }}
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.osdpl.pod.controller.convert_credentials.security_context | nindent 12 }}
      containers:
        - name: osdpl
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
            - run
            - '-n'
            - {{ .Values.osdpl.namespace }}
            - '--standalone'
            - '-m'
            - openstack_controller.controllers.openstackdeployment
            - '-m'
            - openstack_controller.controllers.probe
            - '-L'
            - 'http://0.0.0.0:32768/healthz'
          env:
            - name: OSCTL_HEARTBEAT_PEERING_OBJECT_NAME
              value: openstack-controller.osdpl
            {{- range $optionName, $optionValue := .Values.osdpl.settings.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
            {{- range $optionName, $optionValue := .Values.osdpl.settings.osdpl.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
            - name: OSDPL_IAM_DATA
              value: '{{ toJson .Values.iam }}'
            - name: OSCTL_PROXY_DATA
              value: '{{ toJson .Values.global.proxy }}'
            - name: OSCTL_POD_NETWORKS_DATA
              value: '{{ toJson .Values.global.podNetworks }}'
{{ tuple . | include "openstack-controller.common_env" | indent 12 }}
          livenessProbe:
            exec:
              command:
                - curl
                - http://127.0.0.1:32768/healthz
            {{- toYaml .Values.osdpl.pod.controller.osdpl.liveness.params | nindent 12}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.osdpl.pod.controller.osdpl.security_context | nindent 12 }}
          volumeMounts:
            - name: os-clouds
              mountPath: /etc/openstack/
            - name: openstack-controller-config
              mountPath: /etc/openstack-controller/conf.d/
        - name: secrets
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
            - run
            - '-n'
            - {{ .Values.osdpl.namespace }}
            - '--standalone'
            - '-m'
            - openstack_controller.controllers.secrets
            - '-m'
            - openstack_controller.controllers.probe
            - '-L'
            - 'http://0.0.0.0:32770/healthz'
          env:
            - name: OSCTL_HEARTBEAT_PEERING_OBJECT_NAME
              value: openstack-controller.secrets
            {{- range $optionName, $optionValue := .Values.osdpl.settings.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
            {{- range $optionName, $optionValue := .Values.osdpl.settings.secrets.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
{{ tuple . | include "openstack-controller.common_env" | indent 12 }}
          livenessProbe:
            exec:
              command:
                - curl
                - http://127.0.0.1:32770/healthz
            {{- toYaml .Values.osdpl.pod.controller.secrets.liveness.params | nindent 12}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.osdpl.pod.controller.secrets.security_context | nindent 12 }}
          volumeMounts:
            - name: os-clouds
              mountPath: /etc/openstack/
            - name: openstack-controller-config
              mountPath: /etc/openstack-controller/conf.d/
        - name: health
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
            - run
            - '-n'
            - {{ .Values.osdpl.namespace }}
            - '--standalone'
            - '-m'
            - openstack_controller.controllers.health
            - '-m'
            - openstack_controller.controllers.probe
            - '-L'
            - 'http://0.0.0.0:32771/healthz'
          env:
            - name: OSCTL_HEARTBEAT_PEERING_OBJECT_NAME
              value: openstack-controller.health
            {{- range $optionName, $optionValue := .Values.osdpl.settings.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
            {{- range $optionName, $optionValue := .Values.osdpl.settings.health.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
{{ tuple . | include "openstack-controller.common_env" | indent 12 }}
          livenessProbe:
            exec:
              command:
                - curl
                - http://127.0.0.1:32771/healthz
            {{- toYaml .Values.osdpl.pod.controller.health.liveness.params | nindent 12}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.osdpl.pod.controller.health.security_context | nindent 12 }}
          volumeMounts:
            - name: os-clouds
              mountPath: /etc/openstack/
            - name: openstack-controller-config
              mountPath: /etc/openstack-controller/conf.d/
        - name: node
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
            - run
            - '-n'
            - {{ .Values.osdpl.namespace }}
            - '--standalone'
            - '-m'
            - openstack_controller.controllers.node
            - '-m'
            - openstack_controller.controllers.probe
            - '-L'
            - 'http://0.0.0.0:32772/healthz'
          env:
            - name: OSCTL_HEARTBEAT_PEERING_OBJECT_NAME
              value: openstack-controller.node
            {{- range $optionName, $optionValue := .Values.osdpl.settings.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
            {{- range $optionName, $optionValue := .Values.osdpl.settings.node.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
{{ tuple . | include "openstack-controller.common_env" | indent 12 }}
          livenessProbe:
            exec:
              command:
                - curl
                - http://127.0.0.1:32772/healthz
            {{- toYaml .Values.osdpl.pod.controller.node.liveness.params | nindent 12}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.osdpl.pod.controller.node.security_context | nindent 12 }}
          volumeMounts:
            - name: os-clouds
              mountPath: /etc/openstack/
            - name: openstack-controller-config
              mountPath: /etc/openstack-controller/conf.d/
{{ if .Values.node_maintenance.enabled }}
        - name: nodemaintenancerequest
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
            - run
            - '-n'
            - {{ .Values.osdpl.namespace }}
            - '--standalone'
            - '-m'
            - openstack_controller.controllers.maintenance
            - '-m'
            - openstack_controller.controllers.probe
            - '-L'
            - 'http://0.0.0.0:32773/healthz'
          env:
            - name: OSCTL_HEARTBEAT_PEERING_OBJECT_NAME
              value: openstack-controller.nodemaintenancerequest
            - name: OSCTL_LOGGING_CONF
              value: '{{ toJson .Values.osdpl.settings.node_maintenance_request.OSCTL_LOGGING_CONF }}'
            {{- range $optionName, $optionValue := .Values.osdpl.settings.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
            {{- range $optionName, $optionValue := .Values.osdpl.settings.node_maintenance_request.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
{{ tuple . | include "openstack-controller.common_env" | indent 12 }}
          livenessProbe:
            exec:
              command:
                - curl
                - http://127.0.0.1:32773/healthz
            {{- toYaml .Values.osdpl.pod.controller.node_maintenance_request.liveness.params | nindent 12}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.osdpl.pod.controller.node_maintenance_request.security_context | nindent 12 }}
          volumeMounts:
            - name: os-clouds
              mountPath: /etc/openstack/
            - name: openstack-controller-config
              mountPath: /etc/openstack-controller/conf.d/
{{ end }}
        - name: ceph-secrets
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
            - run
            - '-n'
            - {{ .Values.ceph.cephSharedNamespace}}
            - '--standalone'
            - '-m'
            - openstack_controller.controllers.ceph.secrets
            - '-m'
            - openstack_controller.controllers.probe
            - '-L'
            - 'http://0.0.0.0:32774/healthz'
          env:
            - name: OSCTL_HEARTBEAT_PEERING_OBJECT_NAME
              value: openstack-controller.ceph.secrets
            {{- range $optionName, $optionValue := .Values.osdpl.settings.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
{{ tuple . | include "openstack-controller.common_env" | indent 12 }}
          livenessProbe:
            exec:
              command:
                - curl
                - http://127.0.0.1:32774/healthz
            {{- toYaml .Values.osdpl.pod.controller.ceph_secrets.liveness.params | nindent 12}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.osdpl.pod.controller.ceph_secrets.security_context | nindent 12 }}
          volumeMounts:
            - name: os-clouds
              mountPath: /etc/openstack/
            - name: openstack-controller-config
              mountPath: /etc/openstack-controller/conf.d/
        - name: osdplstatus
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
            - run
            - '-n'
            - {{ .Values.osdpl.namespace }}
            - '--standalone'
            - '-m'
            - openstack_controller.controllers.openstackdeploymentstatus
            - '-m'
            - openstack_controller.controllers.probe
            - '-L'
            - 'http://0.0.0.0:32775/healthz'
          env:
            - name: OSCTL_HEARTBEAT_PEERING_OBJECT_NAME
              value: openstack-controller.osdplstatus
            {{- range $optionName, $optionValue := .Values.osdpl.settings.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
            {{- range $optionName, $optionValue := .Values.osdpl.settings.osdplstatus.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
{{ tuple . | include "openstack-controller.common_env" | indent 12 }}
          livenessProbe:
            exec:
              command:
                - curl
                - http://127.0.0.1:32775/healthz
            {{- toYaml .Values.osdpl.pod.controller.osdplstatus.liveness.params | nindent 12}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.osdpl.pod.controller.osdplstatus.security_context | nindent 12 }}
          volumeMounts:
            - name: os-clouds
              mountPath: /etc/openstack/
            - name: openstack-controller-config
              mountPath: /etc/openstack-controller/conf.d/
        - name: osdplsecret
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
            - run
            - '-n'
            - {{ .Values.osdpl.namespace }}
            - '--standalone'
            - '-m'
            - openstack_controller.controllers.openstackdeploymentsecret
            - '-m'
            - openstack_controller.controllers.probe
            - '-L'
            - 'http://0.0.0.0:32776/healthz'
          env:
            - name: OSCTL_HEARTBEAT_PEERING_OBJECT_NAME
              value: openstack-controller.osdplsecret
            {{- range $optionName, $optionValue := .Values.osdpl.settings.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
            {{- range $optionName, $optionValue := .Values.osdpl.settings.osdplsecret.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
{{ tuple . | include "openstack-controller.common_env" | indent 12 }}
          livenessProbe:
            exec:
              command:
                - curl
                - http://127.0.0.1:32776/healthz
            {{- toYaml .Values.osdpl.pod.controller.osdplsecret.liveness.params | nindent 12}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.osdpl.pod.controller.osdplsecret.security_context | nindent 12 }}
          volumeMounts:
            - name: os-clouds
              mountPath: /etc/openstack/
            - name: openstack-controller-config
              mountPath: /etc/openstack-controller/conf.d/
        - name: tf-secrets
          image: {{ tuple . .Values.image | include "getImageUrl" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
            - run
            - '-n'
            - {{ .Values.tf.sharedNamespace }}
            - '--standalone'
            - '-m'
            - openstack_controller.controllers.tf.secrets
            - '-m'
            - openstack_controller.controllers.probe
            - '-L'
            - 'http://0.0.0.0:32777/healthz'
          env:
            - name: OSCTL_HEARTBEAT_PEERING_OBJECT_NAME
              value: openstack-controller.tf.secrets
            {{- range $optionName, $optionValue := .Values.osdpl.settings.raw }}
            - name: {{ $optionName }}
              value: "{{ $optionValue }}"
            {{- end }}
{{ tuple . | include "openstack-controller.common_env" | indent 12 }}
          livenessProbe:
            exec:
              command:
                - curl
                - http://127.0.0.1:32777/healthz
            {{- toYaml .Values.osdpl.pod.controller.tf_secrets.liveness.params | nindent 12}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.osdpl.pod.controller.tf_secrets.security_context | nindent 12 }}
          volumeMounts:
            - name: os-clouds
              mountPath: /etc/openstack/
            - name: openstack-controller-config
              mountPath: /etc/openstack-controller/conf.d/
      volumes:
        - name: openstack-controller-config
          configMap:
            name: openstack-controller-config
            defaultMode: 0555
        - name: os-clouds
          secret:
            secretName: keystone-os-clouds
            defaultMode: 365
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
