artifacts:
  images_base_url: docker-kaas-local.artifactory.mirantis.com
  binary_base_url: https://binary.mirantis.com

common:
  charts:
    releases:
      namespace: openstack

features:
  services:
    - block-storage
    - compute
    - dns
    - identity
    - dashboard
    - image
    - ingress
    - database
    - memcached
    - networking
    - orchestration
    - messaging
{%- if openstack_version not in ['queens', 'rocky'] %}
    - placement
{%- endif %}
    - coordination
  glance:
    backend: ceph
  cinder:
    volume:
      backend: ceph
    backup:
      backend: ceph
  neutron:
    backend: tungstenfabric
  database:
    local_volumes:
      enabled: true
  ssl:
    public_endpoints:
      enabled: true
  stacklight:
    enabled: false
    user:
      username: stacklight
services:
  database:
    mariadb:
      values:
        conf:
          database_conf:
            mysqld:
              wsrep_provider_options:
                gcache.size: 1024M
  compute:
    nova:
      values:
        bootstrap:
          structured:
            flavors:
              options:
                m1.extra_tiny_test:
                  disk: 5
                  name: m1.extra_tiny_test
                  ram: 256
                  vcpus: 1
                m1.tiny_test:
                  disk: 5
                  name: m1.tiny_test
                  ram: 512
                  vcpus: 1
  tempest:
    tempest:
      values:
        conf:
          # NOTE(vsaienko): disable cleanup explicitly to avoid production data loss.
          # DANGER: do not enable this on production environment.
          cleanup:
            enabled: False
          convert_to_uuid:
            network:
              public_network_id: public
            compute:
              image_ref: Cirros-5.1
              image_ref_alt: Cirros-5.1
              flavor_ref:  m1.extra_tiny_test
              flavor_ref_alt: m1.tiny_test
          blacklist:
            - (?:tempest\.fake\.test)
            # Skip neutron tempest plugin tests that are already contains in tempest
            - (?:neutron_tempest_plugin.api.admin.test_agent_management)
            - (?:neutron_tempest_plugin.api.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_add_remove_network_from_dhcp_agent)
            - (?:neutron_tempest_plugin.api.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_list_dhcp_agent_hosting_network)
            - (?:neutron_tempest_plugin.api.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_list_networks_hosted_by_one_dhcp)
            - (?:neutron_tempest_plugin.api.admin.test_quotas.QuotasTest.test_quotas)
            - (?:neutron_tempest_plugin.api.admin.test_routers_dvr)
            - (?:neutron_tempest_plugin.api.test_dhcp_ipv6)
            - (?:neutron_tempest_plugin.api.test_metering_extensions)
            - (?:neutron_tempest_plugin.api.test_networks.NetworksTestJSON.test_show_network)
            - (?:neutron_tempest_plugin.api.test_security_groups.SecGroupTest.test_create_list_update_show_delete_security_group)
            - (?:neutron_tempest_plugin.api.test_service_type_management.ServiceTypeManagementTest.test_service_provider_list)
            - (?:neutron_tempest_plugin.api.test_flavors_extensions.TestFlavorsIpV6TestJSON.test_list_service_profiles)
            - (?:neutron_tempest_plugin.api.test_flavors_extensions.TestFlavorsJson.test_list_service_profiles)
            - (?:neutron_tempest_plugin.api.test_flavors_extensions.TestFlavorsIpV6TestJSON.test_show_service_profile)
            - (?:neutron_tempest_plugin.api.test_flavors_extensions.TestFlavorsJson.test_show_service_profile)
            - (?:neutron_tempest_plugin.api.test_routers)
            - (?:neutron_tempest_plugin.api.test_allowed_address_pair.AllowedAddressPairIpV6TestJSON)
            - (?:neutron_tempest_plugin.api.test_allowed_address_pair.AllowedAddressPairTestJSON)
            - (?:neutron_tempest_plugin.api.test_extra_dhcp_options.ExtraDHCPOptionsIpV6TestJSON)
            - (?:neutron_tempest_plugin.api.test_extra_dhcp_options.ExtraDHCPOptionsTestJSON)
            # Skip unsupported Tungsenfabric tests
            # TODO(vsaienko): remove when PRODX-3721 resolved.
            - (?:tempest.api.network.test_subnetpools_extensions.SubnetPoolsTestJSON)
            - (?:neutron_tempest_plugin.api.test_subnetpool_prefix_ops)
            - (?:neutron_tempest_plugin.api.test_subnetpools)
            - (?:neutron_tempest_plugin.api.test_subnetpools_negative)
            # TODO: remove when PRODX-4076 resolved.
            - (?:tempest.api.network.test_networks.Networks(|IpV6)Test.test_external_network_visibility)
            # TODO(ibumarskov): remove when PRODX-3815 (VSRx configuration) resolved.
            - (?:tempest.api.compute.servers.test_attach_interfaces.AttachInterfacesUnderV243Test.test_add_remove_fixed_ip)
            - (?:tempest.api.compute.servers.test_server_actions.ServerActionsTestJSON.test_reboot_server_hard)
            - (?:tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops)
            - (?:tempest.scenario.test_server_basic_ops.TestServerBasicOps.test_server_basic_ops)
            # TODO(ibumarskov): not supported by TF (PRODX-4410)
            - (?:tempest.api.network.test_networks.Networks(|IpV6)Test.test_update_subnet_gw_dns_host_routes_dhcp)
            # TODO(ibumarskov): not supported by TF (PRODX-4417)
            - (?:tempest.api.network.test_ports.Ports(|IpV6)TestJSON.test_create_update_port_with_second_ip)
            # TODO(ibumarskov): functionality isn't implemented (PRODX-4419, PROD-21671)
            - (?:tempest.api.network.test_ports.Ports(|IpV6)TestJSON.test_update_port_with_security_group_and_extra_attributes)
            - (?:tempest.api.network.test_ports.Ports(|IpV6)TestJSON.test_update_port_with_two_security_groups_and_extra_attributes)
          script: |
            tempest run --config-file /etc/tempest/tempest.conf -w 4 --smoke --blacklist-file  /etc/tempest/test-blacklist
          tempest:
            identity:
              ca_certificates_file: /certs/ca-bundle.pem
            #TODO(mshalamov): Will be removed during process of completing PRODX-1192
            compute:
              fixed_network_name: tempest-fixed-net
              min_compute_nodes: 2
            #TODO(mshalamov): Will be removed during process of completing PRODX-1192
            compute-feature-enabled:
              cold_migration: true
              resize: true
            image:
              build_timeout: 600
            load_balancer:
              lb_build_timeout: 1500
            validation:
              image_ssh_password: gocubsgo
              image_ssh_user: cirros
            network:
              shared_physical_network: false
              floating_network_name: public
              #TODO(ibumarskov): limitation from commit of https://bugs.launchpad.net/juniperopenstack/+bug/1720118
              project_network_cidr: 10.100.0.0/24
              project_network_v6_cidr: 2003::/120
              project_network_v6_mask_bits: 124
              #TODO(ibumarskov): feature not implemented https://bugs.launchpad.net/juniperopenstack/+bug/1604568
              ipv6_subnet_attributes: false
            #TODO: Will be automated soon in filters.
            network-feature-enabled:
              api_extensions:
                # not supported by TungstenFabric
                # - address-scope
                # - default-subnetpools
                # - standard-attr-tag
                # - rbac-policies
                # - l3_agent_scheduler
                # - ext-gw-mode
                # - agent
                # - dhcp_agent_scheduler
                # - extraroute
                # - dvr
                # - net-mtu
                # - tag
                - network-ip-availability
                - network_availability_zone
                - auto-allocated-topology
                - binding
                - subnet_allocation
                - external-net
                - flavors
                - availability_zone
                - quotas
                - l3-ha
                - provider
                - multi-provider
                - subnet-service-types
                - standard-attr-timestamp
                - service-type
                - l3-flavors
                - port-security
                - extra_dhcp_opt
                - standard-attr-revisions
                - pagination
                - sorting
                - security-group
                - router_availability_zone
                - standard-attr-description
                - router
                - allowed-address-pairs
                - project-id
                - filter-validation
                - dns-domain-ports
                - dns-integration
            volume-feature-enabled:
              api_v1: false
              api_v2: false
              api_v3: true
              cluster_active_active: true
          tempest_logging:
            handler_file:
              args: ('/var/lib/tempest/data/tempest.log',)
              class: FileHandler
              formatter: tests
              level: DEBUG
            handler_stdout:
              level: WARN
            handlers:
              keys: file,stdout
            logger_root:
              handlers: stdout,file
              level: DEBUG
            logger_tempest:
              handlers: stdout,file
              level: DEBUG

        manifests:
          job_bootstrap: true
