artifacts:
  images_base_url: docker-kaas-local.artifactory.mirantis.com
  binary_base_url: https://binary.mirantis.com

common:
  charts:
    releases:
      namespace: openstack

features:
  services:
    - block-storage
    - compute
    - dns
    - identity
    - dashboard
    - image
    - ingress
    - database
    - memcached
    - networking
    - orchestration
    - messaging
    - load-balancer
{%- if openstack_version not in ['queens', 'rocky'] %}
    - placement
{%- endif %}
  glance:
    backend: ceph
  cinder:
    volume:
      backend: ceph
    backup:
      backend: ceph
  neutron:
    backend: ovs
  database:
    local_volumes:
      enabled: true
  ssl:
    public_endpoints:
      enabled: true
  stacklight:
    enabled: true
    user:
      username: stacklight
services:
  database:
    mariadb:
      values:
        conf:
          database_conf:
            mysqld:
              wsrep_provider_options:
                gcache.size: 1024M
  image:
    glance:
      values:
        bootstrap:
          enabled: true
          ks_user: admin
          structured:
            images:
              cirros:
                container_format: bare
                image_file: cirros-0.4.0-x86_64-disk.img
                image_type: qcow2
                min_disk: 1
                name: Cirros-4.0
                private: false
                properties:
                  os_distro: cirros
                source_url: https://artifactory.mcp.mirantis.net/artifactory/test-images/
              fedora:
                container_format: bare
                image_file: Fedora-Cloud-Base-27-1.6.x86_64.qcow2
                image_type: qcow2
                min_disk: 1
                name: Fedora-27-1.6
                private: false
                properties:
                  os_distro: fedora
                source_url: https://artifactory.mcp.mirantis.net/artifactory/test-images/
  compute:
    nova:
      values:
        bootstrap:
          structured:
            flavors:
              options:
                m1.extra_tiny_test:
                  disk: 5
                  name: m1.extra_tiny_test
                  ram: 256
                  vcpus: 1
                m1.tiny_test:
                  disk: 5
                  name: m1.tiny_test
                  ram: 512
                  vcpus: 1
  tempest:
    tempest:
      values:
        conf:
          convert_to_uuid:
            network:
              public_network_id: public
            compute:
              image_ref: Cirros-4.0
              image_ref_alt: Cirros-4.0
              flavor_ref:  m1.extra_tiny_test
              flavor_ref_alt: m1.tiny_test
          blacklist:
            - (?:tempest\.fake\.test)
          script: |
            tempest run --config-file /etc/tempest/tempest.conf -w 4 --smoke --blacklist-file  /etc/tempest/test-blacklist
          tempest:
            identity:
              ca_certificates_file: /certs/ca-bundle.pem
            #TODO(mshalamov): Will be removed during process of completing PRODX-1192
            compute:
              min_compute_nodes: 2
            #TODO(mshalamov): Will be removed during process of completing PRODX-1192
            compute-feature-enabled:
              cold_migration: true
              resize: true
            validation:
              image_ssh_password: gocubsgo
              image_ssh_user: cirros
            network:
              shared_physical_network: false
              floating_network_name: public
            #TODO: Will be automated soon in filters.
            network-feature-enabled:
              api_extensions:
                - default-subnetpools
                - network-ip-availability
                - network_availability_zone
                - auto-allocated-topology
                - ext-gw-mode
                - binding
                - agent
                - subnet_allocation
                - l3_agent_scheduler
                - tag
                - external-net
                - flavors
                - net-mtu
                - availability_zone
                - quotas
                - l3-ha
                - provider
                - multi-provider
                - address-scope
                - extraroute
                - subnet-service-types
                - standard-attr-timestamp
                - service-type
                - l3-flavors
                - port-security
                - extra_dhcp_opt
                - standard-attr-revisions
                - pagination
                - sorting
                - security-group
                - dhcp_agent_scheduler
                - router_availability_zone
                - rbac-policies
                - standard-attr-description
                - router
                - allowed-address-pairs
                - project-id
                - dvr
                - filter-validation
                - standard-attr-tag
                - dns-domain-ports
                - dns-integration
        manifests:
          job_bootstrap: true
