common:
  charts:
    releases:
      version: 0.1.0
      namespace: openstack
      values:
        images:
          tags:
            scripted_test: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            barbican_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/barbican:stein-bionic-20190923180012
            barbican_api: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/barbican:stein-bionic-20190923180012
            bootstrap: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            cinder_api: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/cinder:stein-bionic-20190923180012
            cinder_backup: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/cinder:stein-bionic-20190923180012
            cinder_backup_storage_init: docker-prod-local.docker.mirantis.net/mcp/ceph-config-helper:nightly
            cinder_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/cinder:stein-bionic-20190923180012
            cinder_scheduler: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/cinder:stein-bionic-20190923180012
            cinder_storage_init: docker-prod-local.docker.mirantis.net/mcp/ceph-config-helper:nightly
            cinder_volume: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/cinder:stein-bionic-20190923180012
            cinder_volume_usage_audit: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/cinder:stein-bionic-20190923180012
            db_drop: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            db_init: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            dep_check: docker-prod-local.docker.mirantis.net/mcp/kubernetes-entrypoint:v0.3.1-20190916150122
            designate_api: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/designate:stein-bionic-20190923180012
            designate_central: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/designate:stein-bionic-20190923180012
            designate_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/designate:stein-bionic-20190923180012
            designate_mdns: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/designate:stein-bionic-20190923180012
            designate_producer: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/designate:stein-bionic-20190923180012
            designate_sink: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/designate:stein-bionic-20190923180012
            designate_worker: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/designate:stein-bionic-20190923180012
            glance_api: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/glance:stein-bionic-20190923180012
            glance_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/glance:stein-bionic-20190923180012
            glance_registry: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/glance:stein-bionic-20190923180012
            glance_storage_init: docker-prod-local.docker.mirantis.net/mcp/ceph-config-helper:nightly
            heat_api: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            heat_cfn: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            heat_cloudwatch: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            heat_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            heat_engine: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            heat_engine_cleaner: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            heat_purge_deleted: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            horizon: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/horizon:stein-bionic-20190923180012
            horizon_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/horizon:stein-bionic-20190923180012
            image_repo_sync: docker-prod-local.docker.mirantis.net/mcp/docker:17.07.0-20190916150122
            keystone_api: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-bionic-20190923180012
            keystone_credential_cleanup: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            keystone_credential_rotate: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-bionic-20190923180012
            keystone_credential_setup: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-bionic-20190923180012
            keystone_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-bionic-20190923180012
            keystone_domain_manage: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-bionic-20190923180012
            keystone_fernet_rotate: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-bionic-20190923180012
            keystone_fernet_setup: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/keystone:stein-bionic-20190923180012
            ks_endpoints: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            ks_service: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            ks_user: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            keystone_federations_create: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            neutron_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190923180012
            neutron_dhcp: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190923180012
            neutron_l3: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190923180012
            neutron_linuxbridge_agent: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190923180012
            neutron_metadata: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190923180012
            neutron_openvswitch_agent: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190923180012
            neutron_server: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/neutron:stein-bionic-20190923180012
            nova_api: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/nova:stein-bionic-20190923180012
            nova_cell_setup: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/nova:stein-bionic-20190923180012
            nova_cell_setup_init: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            nova_compute: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/nova:stein-bionic-20190923180012
            nova_compute_ironic: docker.io/kolla/ubuntu-source-nova-compute-ironic:ocata
            nova_compute_ssh: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/nova:stein-bionic-20190923180012
            nova_conductor: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/nova:stein-bionic-20190923180012
            nova_consoleauth: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/nova:stein-bionic-20190923180012
            nova_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/nova:stein-bionic-20190923180012
            nova_novncproxy: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/nova:stein-bionic-20190923180012
            nova_novncproxy_assets: docker.io/kolla/ubuntu-source-nova-novncproxy:ocata
            nova_placement: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/nova:stein-bionic-20190923180012
            nova_scheduler: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/nova:stein-bionic-20190923180012
            nova_service_cleaner: docker-prod-local.docker.mirantis.net/mcp/ceph-config-helper:nightly
            octavia_api: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/octavia:stein-bionic-20190923180012
            octavia_db_sync: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/octavia:stein-bionic-20190923180012
            octavia_health_manager: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/octavia:stein-bionic-20190923180012
            octavia_hm_port: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/octavia:stein-bionic-20190923180012
            octavia_housekeeping: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/octavia:stein-bionic-20190923180012
            openvswitch_db_server: docker-prod-local.docker.mirantis.net/mcp/openvswitch:2.11-bionic-1561381942782
            openvswitch_vswitchd: docker-prod-local.docker.mirantis.net/mcp/openvswitch:2.11-bionic-1561381942782
            create_resources: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            octavia_worker: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/octavia:stein-bionic-20190923180012
            mariadb: docker-prod-local.docker.mirantis.net/mirantis/general/mariadb:10.2.23-bionic-20190924031713
            prometheus_create_mysql_user: docker-prod-local.docker.mirantis.net/mirantis/general/mariadb:10.2.23-bionic-20190924031713
            prometheus_mysql_exporter: docker-prod-local.docker.mirantis.net/stacklight/mysqld-exporter:v0.11.0
            prometheus_mysql_exporter_helm_tests: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            mariadb_backup: docker-prod-local.docker.mirantis.net/mirantis/general/mariadb:10.2.23-bionic-20190924031713
            mariadb_scripted_test: docker-prod-local.docker.mirantis.net/mirantis/general/mariadb:10.2.23-bionic-20190924031713
            rabbit_init: docker.io/rabbitmq:3.7-management
            powerdns: docker-prod-local.docker.mirantis.net/mcp/powerdns:4.1-alpine-1566452831101
            prometheus_rabbitmq_exporter: docker-prod-local.docker.mirantis.net/stacklight/rabbitmq-exporter:v0.29.0
            prometheus_rabbitmq_exporter_helm_tests: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            rabbitmq_init: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            rabbitmq: docker-prod-local.docker.mirantis.net/mcp/rabbitmq:3.7.15-bionic-1560515813082
            rabbitmq_scripted_test: docker-prod-local.docker.mirantis.net/mcp/rabbitmq-management:3.7.15-bionic-1560516651125
            tempest_run_tests: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/tempest:stein-bionic-20190923180012
            tempest-uuids-init: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/heat:stein-bionic-20190923180012
            glance_metadefs_load: docker-dev-virtual.docker.mirantis.net/mirantis/oscore/oh/glance:stein-bionic-20190923180012
            memcached: docker-prod-local.docker.mirantis.net/mcp/memcached:1.5.12-debian-1558605861247
            db_sync: docker-prod-local.docker.mirantis.net/mcp/powerdns:4.1-alpine-1566452831101
            ingress: docker-prod-local.docker.mirantis.net/mcp/nginx-ingress-controller:0.9.0-20190916150122
            error_pages: docker-prod-local.docker.mirantis.net/mcp/defaultbackend:1.0-20190916150122
            prometheus_memcached_exporter: docker-prod-local.docker.mirantis.net/stacklight/memcached-exporter:v0.5.0
    repositories:
    - name: osh
      url: https://harbor.mcp.mirantis.net/chartrepo/mcp-openstack-helm-20190923113658
    - name: osh-infra
      url: https://harbor.mcp.mirantis.net/chartrepo/mcp-openstack-helm-infra-20190920155405
  openstack:
    repo: osh
    values:
      pod:
        replicas:
          api: 3
  infra:
    repo: osh-infra
features:
  messaging:
    dedicated_rabbitmq:
      enabled: true
  database:
    local_volumes:
      enabled: true
  ssl:
    public_endpoints:
      enabled: false
