apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-block-storage
spec:
  releases:
{%- if spec.get('features', {}).get('messaging', {}).get('dedicated_rabbitmq', {}).get('enabled', True) %}
  - name: openstack-cinder-rabbitmq
    chart: {{spec.common.infra.get('repo', spec.common.charts.repo)}}/rabbitmq
    values:
      pod:
        replicas:
          server: 1
      manifests:
        network_policy: false
      volume:
{%- if spec.get('features', {}).get('messaging', {}).get('local_volumes', {}).get('enabled', False) %}
        class_name: local-provisioner
{%- else %}
        class_name: rook-ceph-block
{%- endif %}
      endpoints:
        oslo_messaging: &cinder_endpoints_oslo_messaging
          statefulset:
            replicas: 1
            name: openstack-cinder-rabbitmq-rabbitmq
          hosts:
            default: rabbitmq-cinder
          path: /cinder
{%- endif %}
  - name: openstack-cinder
    chart: {{spec.common.openstack.get('repo', spec.common.charts.repo)}}/cinder
    values:
      pod:
        replicas:
          api: 1
          registry: 1
      storage: ceph
      ceph_client:
        configmap: rook-ceph-config
        user_secret_name: rook-ceph-admin-keyring
      conf:
        ceph:
          pools:
            backup:
              replication: 1
              crush_rule: replicated_ruleset
              chunk_size: 8
            volume:
              replication: 1
              crush_rule: replicated_ruleset
              chunk_size: 8
        cinder:
{%- if spec.get('features', {}).get('cinder', {}).get('backup', {}).get('backend') == 'ceph' %}
          DEFAULT:
            backup_driver: cinder.backup.drivers.ceph.CephBackupDriver
{%- endif %}
      manifests:
        network_policy: false
{%- if spec.get('features', {}).get('messaging', {}).get('dedicated_rabbitmq', {}).get('enabled', True) %}
      endpoints:
        oslo_messaging:
          <<: *cinder_endpoints_oslo_messaging
{%- endif %}
