apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-block-storage
spec:
  releases:
  - name: openstack-cinder
    chart: {{spec.common.charts.repo}}/cinder
    version: {{spec.common.charts.version}}
    values:
      pod:
        replicas:
          api: 1
          registry: 1
      storage: ceph
      ceph_client:
        configmap: rook-ceph-config
        user_secret_name: rook-ceph-admin-keyring
      conf:
        ceph:
          pools:
            backup:
              replication: 1
              crush_rule: replicated_ruleset
              chunk_size: 8
            volume:
              replication: 1
              crush_rule: replicated_ruleset
              chunk_size: 8
      manifests:
        network_policy: false
