apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-compute
spec:
  releases:
{%- if spec.get('features', {}).get('messaging', {}).get('dedicated_rabbitmq', {}).get('enabled', True) %}
  - name: openstack-nova-rabbitmq
    chart: {{spec.common.infra.repo}}/rabbitmq
    values:
      pod:
        replicas:
          server: 1
      manifests:
        network_policy: false
{%- if spec.get('features', {}).get('messaging', {}).get('create_user_credentials', False) %}
        job_users_create: true
{%- endif %}
      volume:
{%- if spec.get('features', {}).get('messaging', {}).get('local_volumes', {}).get('enabled', False) %}
        class_name: local-provisioner
{%- else %}
        class_name: rook-ceph-block
{%- endif %}
      endpoints:
        oslo_messaging: &nova_endpoints_oslo_messaging
          statefulset:
            replicas: 1
            name: openstack-nova-rabbitmq-rabbitmq
          hosts:
            default: rabbitmq-nova
          path: /nova
{%- if spec.get('features', {}).get('messaging', {}).get('create_user_credentials', False) %}
      conf:
        users:
          nova:
            auth:
              service_user:
                username: nova
                password: password
            path: /nova
{%- endif %}
{%- endif %}
  - name: openstack-libvirt
    chart: {{spec.common.infra.repo}}/libvirt
    values:
      images:
        tags:
          libvirt: docker-prod-virtual.docker.mirantis.net/mcp/libvirt:4.0.0-bionic-1554881274591
      manifests:
        network_policy: false
      conf:
        ceph:
          enabled: false
        libvirt:
          listen_addr: 0.0.0.0
  - name: openstack-nova
    chart: {{spec.common.openstack.repo}}/nova
    values:
      manifests:
        network_policy: false
{%- if spec.get('features', {}).get('messaging', {}).get('create_user_credentials', False) %}
        job_rabbit_init: false
{%- endif %}
{%- if spec.get('features', {}).get('messaging', {}).get('dedicated_rabbitmq', {}).get('enabled', True) %}
      endpoints:
        oslo_messaging:
          <<: *nova_endpoints_oslo_messaging
        oslo_messaging_notifications:
          statefulset:
            replicas: 1
            name: openstack-rabbitmq-rabbitmq
          hosts:
            default: rabbitmq-notifications
          path: /openstack
{%- endif %}
#      ceph_client:
#        configmap: rook-ceph-config
#        user_secret_name: rook-ceph-admin-keyring
      conf:
        ceph:
          enabled: false
#          admin_keyring:
#          cinder:
#            user: "cinder"
      #      keyring: AQAHkNFcy0NJLhAAgirzRZJTb35tbwhbMkrIAw==
      #      keyring: null
#            secret_uuid: 457eb676-33da-42ec-9a8c-9293d545c337
        nova:
          libvirt:
            cpu_mode: custom
            cpu_model: kvm64
            virt_type: kvm
        # TODO(vsaienko): unhardcode this interface
        libvirt:
          live_migration_interface: ens3
