{%- set stacklight_enabled = spec.get('features', {}).get('stacklight', {}).get('enabled', False) %}

spec:
  releases:
  - name: openstack-mariadb
    chart: {{spec.common.infra.repo}}/mariadb
    values:
{%- if stacklight_enabled %}
      monitoring:
        prometheus:
          enabled: true
{%- endif %}
      manifests:
        network_policy: false
        job_cluster_wait: true
      endpoints:
        cluster_domain_suffix: {{ spec.domain_name }}
        oslo_db:
          namespace: null
          auth:
            admin:
              username: {{ admin_creds.database.username }}
              password: {{ admin_creds.database.password }}
            sst:
              username: sst
              password: password
            exporter:
              username: exporter
              password: password
      pod:
        replicas:
          server: 3
{%- if spec.get('features', {}).get('database', {}).get('local_volumes', {}).get('enabled', False) %}
        # To have higher level of data redundency in case of local volumes - ensure pods are spread
        # across volumes placed on different nodes
        affinity:
          anti:
            type:
              default: requiredDuringSchedulingIgnoredDuringExecution
{%- endif %}
      volume:
{%- if spec.get('features', {}).get('database', {}).get('local_volumes', {}).get('enabled', False) %}
        class_name: local-provisioner
{%- else %}
        class_name: rook-ceph-block
{%- endif %}
