apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-image
spec:
  releases:
  - name: openstack-glance
    chart: {{spec.common.openstack.get('repo', spec.common.charts.repo)}}/glance
    values:
      pod:
        replicas:
          api: 1
          registry: 1
      storage: rbd
      conf:
        glance:
          DEFAULT:
            enable_v1_api: True
            enable_v2_registry: True
          glance_store:
            rbd_store_crush_rule: replicated_ruleset
      volume:
        class_name: rook-ceph-block
        size: 2Gi
      ceph_client:
        configmap: rook-ceph-config
        user_secret_name: rook-ceph-admin-keyring
      manifests:
        network_policy: false
