apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-orchestration
spec:
  releases:
  - name: openstack-heat
    chart: {{spec.common.openstack.get('repo', spec.common.charts.repo)}}/heat
    values:
      manifests:
        network_policy: false
