apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-ingress
spec:
  releases:
  - name: ingress-openstack
    chart: {{spec.common.infra.repo}}/ingress
    values:
      manifests:
        network_policy: false
