spec:
  releases:
  - name: ingress-openstack
    chart: {{spec.common.infra.repo}}/ingress
    values:
      manifests:
        network_policy: false
      endpoints:
        cluster_domain_suffix: {{ spec.domain_name }}
