apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-identity
spec:
  releases:
  - name: openstack-keystone
    chart: {{spec.common.openstack.get('repo', spec.common.charts.repo)}}/keystone
    values:
      manifests:
        network_policy: false
