apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-identity
spec:
  releases:
  - name: openstack-keystone
    chart: {{spec.common.charts.repo}}/keystone
    version: {{spec.common.charts.version}}
    values:
      manifests:
        network_policy: false
