apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-database
spec:
  releases:
  - name: openstack-mariadb
    chart: {{spec.common.charts.repo}}/mariadb
    version: {{spec.common.charts.version}}
    values:
      manifests:
        network_policy: false
      pod:
        replicas:
          server: 1
      volume:
        class_name: rook-ceph-block
