apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-database
spec:
  repositories:
  - name: oscore
    url: 'https://artifactory.mcp.mirantis.net/artifactory/helm-dev-virtual/'
  releases:
  - name: openstack-mariadb
    chart: oscore/mariadb
    version: 0.1.0
    namespace: default
    values:
      manifests:
        network_policy: false
      pod:
        replicas:
          server: 1
