apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-memcached
spec:
  releases:
  - name: openstack-memcached
    chart: {{spec.common.infra.repo}}/memcached
    values:
      manifests:
        network_policy: false
