apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-compute
spec:
  repositories:
  - name: oscore
    url: 'https://artifactory.mcp.mirantis.net/artifactory/helm-dev-virtual/'
  releases:
  - name: openstack-libvirt
    chart: oscore/libvirt
    version: 0.1.0
    namespace: default
    values:
      images:
        tags:
          libvirt: docker-prod-virtual.docker.mirantis.net/mcp/libvirt:4.0.0-bionic-1554881274591
      manifests:
        network_policy: false
      conf:
        ceph:
          enabled: false
  - name: openstack-nova
    chart: oscore/nova
    version: 0.1.0
    namespace: default
    values:
      manifests:
        network_policy: false
#      ceph_client:
#        configmap: rook-ceph-config
#        user_secret_name: rook-ceph-admin-keyring
      conf:
        ceph:
          enabled: false
#          admin_keyring:
#          cinder:
#            user: "cinder"
      #      keyring: AQAHkNFcy0NJLhAAgirzRZJTb35tbwhbMkrIAw==
      #      keyring: null
#            secret_uuid: 457eb676-33da-42ec-9a8c-9293d545c337
        nova:
          libvirt:
            cpu_mode: custom
            cpu_model: kvm64
            virt_type: kvm
