apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-orchestration
spec:
  releases:
{%- if spec.get('features', {}).get('messaging', {}).get('dedicated_rabbitmq', {}).get('enabled', True) %}
  - name: openstack-heat-rabbitmq
    chart: {{spec.common.infra.repo}}/rabbitmq
    values:
      pod:
        replicas:
          server: 1
      manifests:
        network_policy: false
{%- if spec.get('features', {}).get('messaging', {}).get('create_user_credentials', False) %}
        job_users_create: true
{%- endif %}
      volume:
{%- if spec.get('features', {}).get('messaging', {}).get('local_volumes', {}).get('enabled', False) %}
        class_name: local-provisioner
{%- else %}
        class_name: rook-ceph-block
{%- endif %}
      endpoints:
        oslo_messaging: &heat_endpoints_oslo_messaging
          statefulset:
            replicas: 1
            name: openstack-heat-rabbitmq-rabbitmq
          hosts:
            default: rabbitmq-heat
            path: /heat
{%- if spec.get('features', {}).get('messaging', {}).get('create_user_credentials', False) %}
      conf:
        users:
          heat:
            auth:
              service_user:
                username: heat
                password: password
            path: /heat
{%- endif %}
{%- endif %}
  - name: openstack-heat
    chart: {{spec.common.openstack.repo}}/heat
    values:
      manifests:
        network_policy: false
{%- if spec.get('features', {}).get('messaging', {}).get('create_user_credentials', False) %}
        job_rabbit_init: false
{%- endif %}
{%- if spec.get('features', {}).get('messaging', {}).get('dedicated_rabbitmq', {}).get('enabled', True) %}
      endpoints:
        oslo_messaging:
          <<: *heat_endpoints_oslo_messaging
        oslo_messaging_notifications:
          statefulset:
            replicas: 1
            name: openstack-rabbitmq-rabbitmq
          hosts:
            default: rabbitmq-notifications
          path: /openstack
{%- endif %}
