apiVersion: lcm.mirantis.com/v1alpha1
kind: HelmBundle
metadata:
  name: openstack-tempest
spec:
  releases:
  - name: openstack-tempest
    chart: {{spec.common.openstack.repo}}/tempest
    values:
      manifests:
        network_policy: false
      pod:
        replicas:
          server: 1
      pvc:
        storage_class: rook-ceph-block
      endpoints:
        identity:
          auth:
            admin:
              region_name: {{ spec.features.keystone.users.admin.get('region_name', 'RegionOne') }}
              username: {{ spec.features.keystone.users.admin.username }}
              password: {{ spec.features.keystone.users.admin.password }}
              project_name: {{ spec.features.keystone.users.admin.get('project_name', 'admin') }}
              user_domain_name: {{ spec.features.keystone.users.admin.get('user_domain_name', 'default') }}
              project_domain_name: {{ spec.features.keystone.users.admin.get('project_domain_name', 'default') }}
              default_domain_id: {{ spec.features.keystone.users.admin.get('default_domain_id', 'default') }}
      conf:
        tempest: {{ spec | generate_tempest_config(helmbundles_body) }}
