- name: label k8s controllers
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ ansible_hostname }}"
        labels: "{{ oc_k8s_node_labels['controller'] }}"
  when: oc_k8s_controller_node

- name: label k8s computes
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ ansible_hostname }}"
        labels: "{{ oc_k8s_node_labels['compute'] }}"
  when: oc_k8s_compute_node
