---
all:
  vars:
    ansible_ssh_user: ubuntu
    k0s_worker_on_controller: true
    oc_binary_base_url: https://artifactory.mcp.mirantis.net/artifactory/binary-dev-kaas-virtual
    oc_images_base_url: docker-dev-kaas-virtual.docker.mirantis.net
  hosts:
    oc-virtual-lab-server-ctl-01:
      ansible_host: 127.0.0.1

  children:
    computes:
      hosts:
        oc-virtual-lab-server-ctl-01:
    controllers:
      hosts:
        oc-virtual-lab-server-ctl-01:
    k0s_controllers:
      hosts:
        oc-virtual-lab-server-ctl-01:
